{if !empty($tasks)}
	<table id="task-stats" cellspacing="0">
		<thead>
			<th>#</th>
			<th>název</th>
			<th>nejhorší</th>
			<th>nejlepší</th>
			<th>průměrný</th>
			<th>správně</th>
			<th>špatně</th>
		</thead>
		{foreach $tasks AS $task}
			<tr{if $iterator->isEven()} class="even"{/if}>
				<td>{$task->code_name}</td>
				<td>{$task->name}</td>
				<td>{$task->worst_time|timeOnly}</td>
				<td>{$task->best_time|timeOnly}</td>
				<td>{$task->avg_time|timeOnly}</td>
				<td>{$task->count_correct_answer}</td>
				<td>{$task->count_incorrect_answer}</td>
			</tr>
		{/foreach}
	</table>
{/if}