{extends layout.phtml}

{block #content}
<div id="submenu">
        <a href="{$baseUri}download/interlos_III(2011).pdf" title="Interlos III 2011">
                <img src="{$baseUri}download/interlos2011.jpg" alt="Interlos III" style="border: 1px solid #cecece; width:300px;"/>
        </a>    
</div>
<div id="subcontent">
    <div class="flash info">
        Už se nemůžete dočkat? Připravili jsme pro vás <a href="download/interlos-2011-prirucka-hrace.pdf" title="Příručka hráče" style="font-size: 140%;">příručku hráče</a>.
        Nebojte, není dlouhá, je tam však několik užitečných informací ohledně technické stránky soutěže a pár velmi lehkých úloh k rozehřátí.
    </div>
    
<ul>
        <li>Nejen informatická soutěž pořádaná <a href="http://fi.muni.cz" title="Fakulta informatiky MU Brno">Fakultou informatiky MU Brno</a></li>
        <li><strong style="font-size: 120%; text-transform: capitalize">Pozor! Změna termínu!</strong></li>
        <li>Proběhne<strong style="font-size:2em"> v sobotu 12. 11. 2011, 15:00 - 20:00</strong></li>
        <li><strong>Registrace otevřena od 14. 8. 2011 do 11. 11. 2011!</strong></li>
        <li>
                Můžete se těšit na 27 rozmanitých, originálních úloh:
                <ul>
                        <li>Logické úlohy</li>
                        <li>Programátorské příklady</li>
                        <li>Šifry</li>
                        <li>Vyhledávání na internetu</li>
                </ul>
        </li>
        <li>Soutěžit budou 1-5 členné týmy ve třech kategoriích - středoškoláci, vysokoškoláci a ostatní.</li>
        <li>Účast je zcela zdarma</li>
        <li><strong>Hraje se o prestiž</strong></li>
</ul>
<p>
        Další informace najdete v <a href="{link :Frontend:Default:rules}">pravidlech</a>.
</p>


<p>
	Pokud máte jakýkoliv dotaz, připomínku, námět apod.,
	napište nám na naši adresu <a href="mailto:interlos@fi.muni.cz" style="font-size:1.5em">interlos@fi.muni.cz</a>
</p>

<div id="logos">
	<a href="http://muni.cz" title="Masarykova univerzita">
		<img src="http://ganymed.math.muni.cz/intersob/images/logo_mu.gif" alt="Masarykova univerzita"/>
	</a>
	<a href="http://fi.muni.cz" title="Fakulta informatiky MU">
		<img src="http://ganymed.math.muni.cz/intersob/images/logo_fi.gif" alt="Fakulta informatiky Masarykovy univerzity" />
	</a>
	<a href="http://ksi.fi.muni.cz" title="Korespondenční Seminář z Informatiky">
		<img src="{$baseUri}images/ksi-logo-final.png" alt="Korespondenční seminář z informatiky" style="display:inline" />
	</a>
</div>

<!--<h2>Korespondenční seminář z informatiky</h2>-->
<h2>Soutěž INTERLOS vám přináší</h2>
<p>organizátoři <a href="http://ksi.fi.muni.cz" title="Korespondenční Seminář z Informatiky">Korespondenčního Semináře z Informatiky</a> a studenti a učitelé <a href="http://muni.cz" title="Masarykova univerzita">Masarykovy univerzity</a>:</p>

<p>
Radek Pelánek, Jan Rygl, Ondřej Bouda, Jan Papoušek, Miroslav Klimoš, Jana Tůmová, Tereza Doležalová, Martin Křivánek, Jiří Appl, Jan Rusnačko, Terka Procházková, Eva Krásenská, Hana Tužilová, Zuzana Petruchová, Bára Pavlů, Pavlína Livňanská
 </p>

<!--<hr />

<h2>Gratulujeme vítězům ročníku 2010!</h2>
<ul>    
        <li>    
                <strong>Celkově</strong>
                <ol>
                        <li>voy-a-ger</li>
                        <li>Tykadla</li>
                        <li>Pomocná škola</li>
                </ol>   
        </li><li>
                <strong>Středoškoláci</strong>
                <ol>    
                        <li>Žufouni</li>
                        <li>Carpe Diem</li>
                        <li>Heuréka</li>
                </ol>   
        </li><li>
                <strong>Vysokoškoláci</strong>
                <ol>    
                        <li>voy-a-ger</li>
                        <li>Ešte se dohodneme</li>
                        <li>Pařížská modrá</li>
                </ol>   
        </li><li>
                <strong>Ostatní</strong>
                <ol>    
                        <li>Tykadla</li>
                        <li>Pomocná škola</li>
                        <li>Jeníčci</li>
                </ol>   
        </li>   
</ul>-->
</div>

{/block}
