{extends layout.phtml}

{block #content}
    <div id="submenu">
	<ul>
	    <li><a href="#2010">2010</a></li>	
	    <li><a href="#2009">2009</a></li>
	</ul>
    </div>
    <div id="subcontent">
	<h2 id="2010">2010</h2>
        <ul>
	    <li><a href="{link Archive:year2010}">podrobná výsledkovka</a></li>
	    <li>Vítězové celkově: <strong>voy-a-ger</strong> (David "Klička" Klaška, Dominik Tělupil, Hynek "Jemelíček" Jemelík, Sam Říha, Tomáš "Lama" Lamser)</li>
	    <li>Vítězové v kategorii středoškoláci: <strong>Žufouni</strong> (David, Honza, Michal, Petr, Zuzana)</li>
	    <li>Vítězové v kategorii vysokoškoláci: <strong>voy-a-ger</strong> (David "Klička" Klaška, Dominik Tělupil, Hynek "Jemelíček" Jemelík, Sam Říha, Tomáš "Lama" Lamser)</li>
	    <li>Vítězové v kategorii ostatní: <strong>Tykadla</strong> (Bingo , Janka , Kouřa , mtronic , Voda)</li>
	</ul>
	<p>
	    Z tohoto ročníku si můžete stáhnout <a href="{$baseUri}download/years/2010/zadani-all.zip">zadání všech úloh včetně doplňujících souborů</a> nebo přímo <a href="{$baseUri}download/years/2010/sada1">sadu&nbsp;1</a>, <a href="{$baseUri}download/years/2010/sada2">sadu&nbsp;2</a> nebo&nbsp;<a href="{$baseUri}download/years/2010/sada3">sadu&nbsp;3</a>. Chybět samozřejmě nemůže ani <a href="{$baseUri}download/years/2010/reseni.pdf">řešení</a>.
            Můžete se také podívat, jak vypadala <a href="http://www.fi.muni.cz/~xpelanek/interlos/rada">webová stránka k úkolu řada z 2. sady</a>.
	</p>        
	<h2 id="2009">2009</h2>
	<ul>
	    <li><a href="{link Archive:year2009}">podrobná výsledkovka</a></li>
	    <li>Vítězové celkově: <strong>Pomocná škola</strong> (Anička, Jirka, Markéta, Medvěd, Vojta)</li>
	    <li>Vítězové v kategorii středoškoláci: <strong>Faltus Team</strong> (Jaroslav Koliha, Michal Soucha, Milan Válek, Vladimír Nahodil)</li>
	    <li>Vítězové v kategorii vysokoškoláci: <strong>Kokokel</strong> (Jana Medková, Jiří Appl, Myreg Klimoš, Petr Velan, Zbyněk Konečný)    </li>
	    <li>Vítězové v kategorii ostatní: <strong>Pomocná škola</strong> (Anička, Jirka, Markéta, Medvěd, Vojta)</li>
	</ul>
	<p>
	    Z tohoto ročníku si můžete stáhnout <a href="{$baseUri}download/years/2009/zadani-all.zip">zadání všech úloh včetně doplňujících souborů</a> nebo přímo <a href="{$baseUri}download/years/2009/zadani-1.pdf">sadu&nbsp;1</a>, <a href="{$baseUri}download/years/2009/zadani-2.pdf">sadu&nbsp;2</a> nebo&nbsp;<a href="{$baseUri}download/years/2009/zadani-3.pdf">sadu&nbsp;3</a>. Chybět samozřejmě nemůže ani <a href="{$baseUri}download/years/2009/reseni.pdf">řešení</a>.
	</p>

    </div>
{/block}
