{extends layout.phtml}

{block #content}
    <div id="submenu">
	<ul>
	    <li><a href="#participation">Účast ve hře</a></li>
	    <li><a href="#tasks">Úlohy</a></li>
	    <li><a href="#system">Systém hry a bodování</a></li>
	    <li><a href="#equipment">Vybavení</a></li>
	    <li><a href="#advices">Rady</a></li>
	</ul>
    </div>
    <div id="subcontent">
	<ul>
	    <li>Interlos je pětihodinová týmová hra probíhající přes Internet.</li>
	    <li>Týmy řeší zadané úlohy, řešením každé úlohy je krátké heslo, které odesílají přes webový formulář.</li>
	    <li>Za vyřešené úlohy získávají týmy body, během hry týmy stále vidí aktuální výsledkovou listinu.</li>
	</ul>

	<h2 id="participation">Účast ve hře</h2>
	<ul>
	    <li>Hrají týmy skládající se z 1-5 hráčů. </li>
	    <li>
		Každý tým se zařadí do jedné ze 3 kategorií:
		<ul>
		    <li><strong>středoškoláci</strong> - všichni členové týmu musí být studenti střední (nebo základní) školy,</li>
		    <li><strong>vysokoškoláci</strong> - všichni členové týmu musí být studenti vysoké (nebo střední či základní) školy,</li>
		    <li><strong>ostatní</strong> - kdokoliv.</li>
		</ul>
	    </li>
	    <li>Týmy ve všech kategoriích budou mít úplně stejné úlohy. Pro každou kategorii bude samostatná výsledková listina, navíc bude i celková výsledková listina.</li>
	    <li>Účast na hře je zdarma.</li>
	    <li>Odměnou za dobré umístění je prestiž a dobrý pocit, hmotné odměny nejsou.</li>
	    <li>Je zakázána jakákoliv spolupráce mezi týmy.</li>
	    <li>Hra je založena na fair-play. Průběh hry monitorujeme a můžeme tedy odhalit některé způsoby podvádění, nicméně předpokládáme, že hrajete proto, abyste si zahráli, a tudíž že podvádění nemá smysl.</li>
	</ul>

	<h2 id="tasks">Úlohy</h2>
	<ul>
	    <li>Hra spočívá v řešení úloh, po vyřešení každé úlohy získáte kód (heslo), které zadáte do internetového systému.</li>
	    <li>
		Úlohy jsou tří základních typů:
		<ul>
		    <li><strong>Logické úlohy</strong> - úlohy s jasně formulovaným zadáním, které se řeší především pomocí tužky, papíru a hlavy (občas ale může být výhodné použít i počítač),</li>
													  <li><strong>Programátorské a počítačové úlohy</strong> - úlohy s jasně formulovaným zadáním, které se řeší především pomocí počítače - typicky je součástí zadání dlouhý vstup a kódem je výstup programu nad tímto vstupem, může jít ale třeba  i o úlohy, které se řeší pomocí vhodného použití tabulkového editoru, programu pro editaci obrázků či jiného programu, </li>
		    <li><strong>Šifry a nápadové úlohy</strong> - úlohy s nejasným zadáním, u kterých musíte dostat nápad, co s úlohou vůbec dělat - může být potřeba dohledat informace na Internetu, ale může i stačit podívat se na zadaný obrázek ze správného úhlu.</li>
		</ul>
	    </li>
	    <li>Zadání úloh budou zveřejněna ve formátu <acronym title="Portable Document Format">PDF</acronym>. U programátorských úloh bude část zadání zveřejněna jako samostatný textový soubor.</li>
	    <li>Výsledný kód je vždy řetězec číslic nebo velkých písmen anglické abecedy (bez diakritiky). Kód je vždy bez mezer.</li>
	    <li>Abyste se mohli udělat základní představu o co půjde, můžete se podívat na <a href="{link taskExamples}">příklady úloh</a>.</li>
	    <li>Úlohy budou rozmanitých typů a rozmanité obtížnosti (od jednoduchých, které by měl vyřešit skoro každý během pár minut, až po obtížné, které během hry zvládne vyřešit jen málokdo).</li>
	</ul>

	<h2 id="system">Systém hry a bodování</h2>
	<ul>
	    <li>
		Úlohy budou zveřejňovány postupně:
		<ul>
		    <li>První sada: 15:00 (začátek hry).</li>
		    <li>Druhá sada: 16:30 (1:30 po začátku).</li>
		    <li>Třetí sada: 18:00 (3:00 po začátku).</li>
		</ul>
	    </li>
	    <li>Konec hry je ve 20:00 (5:00 po začátku hry). Všechny úlohy je povoleno řešit až do konce hry.</li>
	    <li>Každá sada sestává z 9 úloh (3 úlohy od každého typu). Celkem tedy bude 27 úloh (9 od každého typu).</li>
	    <li>
		Za úlohy získávají týmy body. Bodování zohledňuje pořadí, špatné odpovědi a rovnoměrnost rozdělení typů úloh,
		které tým vyřešil (pokud tým řeší rovnoměrně úlohy různých typů, získává bonus). Konkrétně:
		<ul>
		    <li>Za každou vyřešenou úlohu je (1001-p) bodů, kde p je pořadí týmu u dané úlohy.</li>
		    <li>Za každou špatnou odpověď je postih -10 bodů.</li>
		    <li>Za každou uzavřenou trojici úloh různých typů je bonus 500 bodů.</li>
		</ul>
	    </li>
	    <li>
		Příklad bodování. Předpokládejme, že tým vyřešil jednu programátorskou úlohu na 5. místě, dvě logické úlohy na 2.
		a 13. místě a jednu nápadovou úlohu na 8. místě a celkově odevzdal 6 špatných odpovědí.
		Získá tedy 996 + 999 + 988 + 993 bodů za úlohy, -60 bodů za špatné odpovědi a 500 bodů prémii za jednu uzavřenou trojici úloh různých typů. Celkem tedy: 4416 bodů.
	    </li>
	    <li>
		Za špatnou odpověď se týmu kromě trestných bodů ještě navíc na 30 vteřin zablokuje možnost odevzdávat kódy (prevence proti náhodnému hádání kódu).
	    </li>
	</ul>

	<h2 id="equipment">Vybavení</h2>
	<ul>
	    <li>Počítač s přístupem na Internet (rychlost připojení by neměla být příliš důležitá). Více počítačů může být výhodou (ale není nezbytně nutné).</li>
	    <li>Tiskárna není nutná, ale je velmi vhodná. Barevná tiskárna je výhodou.</li>
	    <li>Papíry, tužky, pastelky, podložky, …</li>
	    <li>Svačina.</li>
	    <li> Maskot týmu (nejlépe los).</li>
	</ul>

	<h2 id="advices">Rady</h2>
	<ul>
	    <li>Název úloh může být návodný (týká se především „nápadových úloh“).</li>
	    <li>Větší tým má výhodu, doporučujeme pětičlenné týmy.</li>
	    <li>Protože jedna třetina úloh je programátorská, vyplatí se mít v týmu alespoň jednoho člověka, který umí alespoň trochu programovat.</li>
	    <li>U hry je důležitou součástí i celková strategie: Které úlohy je výhodné řešit?  Je lepší pracovat společně nebo si práci rozdělit a pracovat samostatně? Kdo rozhoduje, jak si tým rozdělí práci? Během hry budete zavaleni úkoly, zkuste si tedy strategii prodiskutovat dopředu.</li>
	    <li> Během hry máte k dispozici výsledkovou listinu a statistiky úloh - z těchto informací můžete poznat, které úlohy jsou jednoduché a které těžké a tomu můžete přizpůsobit svoji strategii. Sledujte tedy pravidelně výsledkovku!</li>
	    <li> Pamatujte, že důležité je získat kód. Nezáleží na tom, jestli napíšete elegantní program pro univerzální řešení zadaného problému, jestli vymyslíte s tužkou a papírem „hackerské“ řešení pro konkrétní zadání, nebo zda úlohu vyřešíte s využitím něčeho, co najdete na Internetu. U některých úloh mohou být schůdné různé cesty, důležité je umět vybrat tu pravou, pomocí které získáte co nejrychleji kód.</li>
	</ul>
    </div>
{/block}


