{extends layout.phtml}

{block #subcontent}
<p>Zadání sad se v určený čas objeví na následujících adresách:</p>

<ul>
	<li>
		1. sada (od 15:00)
		<ul>
			<li><a href="http://www.fi.muni.cz/~xpelanek/interlos2/sada1/">http://www.fi.muni.cz/~xpelanek/interlos2/sada1/</a></li>
			<li><a href="http://anna.fi.muni.cz/~xpapous1/interlos/sada1/">http://anna.fi.muni.cz/~xpapous1/interlos/sada1/</a></li>
			<li><a href="http://interlos.zimodej.cz/sada1">http://interlos.zimodej.cz/sada1</a></li>
		</ul>
	</li>
	<li>
		2. sada (od 16:30)
		<ul>
			<li><a href="http://www.fi.muni.cz/~xpelanek/interlos2/sada2/">http://www.fi.muni.cz/~xpelanek/interlos2/sada2/</a></li>
			<li><a href="http://anna.fi.muni.cz/~xpapous1/interlos/sada2/">http://anna.fi.muni.cz/~xpapous1/interlos/sada2/</a></li>
			<li><a href="http://interlos.zimodej.cz/sada2">http://interlos.zimodej.cz/sada2</a></li>
		</ul>
   </li>
	<li>
		3. sada (od 18:00)
		<ul>
			<li><a href="http://www.fi.muni.cz/~xpelanek/interlos2/sada3/">http://www.fi.muni.cz/~xpelanek/interlos2/sada3/</a></li>
			<li><a href="http://anna.fi.muni.cz/~xpapous1/interlos/sada3/">http://anna.fi.muni.cz/~xpapous1/interlos/sada3/</a></li>
			<li><a href="http://interlos.zimodej.cz/sada3">http://interlos.zimodej.cz/sada3</a></li>
		</ul>
   </li>
</ul>
<p>
	Kdykoliv je v zadání uvedeno více alternativních webových adres, obsahují všechny adresy stejnou informaci a jsou uvedeny pouze pro zálohu (nikdy tedy není žádná úmyslně skrytá informace v rozdílech mezi verzemi).
</p>
<p>
	V případě výpadku serveru, na kterém běží systém hry (což se nám stalo loni, ovšem pevně věříme, že letos se to již nestane), budou vystaveny "krizové informace" na následující stránce:
	<a href="http://www.fi.muni.cz/~xpelanek/interlos2/">http://www.fi.muni.cz/~xpelanek/interlos2/</a>
</p>

<p>
	Na této stránce se také případně objeví upřesnění k zadání / opravy chyb (opět doufáme a věříme, že ani jedno nebude potřeba). Oznámení tohoto typu se současně objeví také na chatu na stránkách hry.
</p>
<p>
	A ještě několik rad:
</p>
<ul>
	<li>Pokud nemáte barevnou tiskárnu, mějte po ruce pastelky.</li>
	<li>Přečtěte si před hrou ještě jednou pravidla, ať máte jasno v bodování.</li>
	<li>Věnujte pozornost sekci "rady" v pravidlech.</li>
	<li>Zařazení příkladů v kategoriích (programátorské a počítačové, logické, šifry a nápadové) je pouze orientační. Klidně se může stát, že logickou úlohu vyřešíte počítačem a počítačovou úlohu tužkou.</li>
	<li>Připravte si dopředu dobrou svačinku a užijte si to.</li>
</ul>
{/block}