{extends ../layout.phtml}
{block #body}
		<table id="score-stats" cellspacing="0">
			<tr>
				<th>#</th>
				<th>Tým</th>

				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
				<th>P1</th>
				<th>L1</th>
				<th>S1</th>

				<th>P2</th>
				<th>L2</th>
				<th>S2</th>
				<th>P3</th>
				<th>L3</th>
				<th>S3</th>

				<th>P4</th>
				<th>L4</th>
				<th>S4</th>
				<th>P5</th>
				<th>L5</th>
				<th>S5</th>

				<th>P6</th>
				<th>L6</th>
				<th>S6</th>
				<th>P7</th>
				<th>L7</th>
				<th>S7</th>

				<th>P8</th>
				<th>L8</th>
				<th>S8</th>
				<th>P9</th>
				<th>L9</th>
				<th>S9</th>

			</tr>
			<tr>
				<td>1</td>
				<td class="team">Pomocná škola</td>
				<td>29718</td>
				<td>
					4000
				</td>

				<td>
					30
				</td>
				<td class="done">977</td>
				<td class="done">966</td>
				<td class="empty">X</td>
				<td class="done">1000</td>

				<td class="done">977</td>
				<td class="done">985</td>
				<td class="done">1000</td>
				<td class="done">987</td>
				<td class="done">998</td>
				<td class="done">999</td>

				<td class="done">991</td>
				<td class="done">997</td>
				<td class="done">994</td>
				<td class="done">973</td>
				<td class="done">984</td>
				<td class="done">999</td>

				<td class="done">991</td>
				<td class="done">1000</td>
				<td class="done">999</td>
				<td class="done">981</td>
				<td class="done">997</td>
				<td class="done">1000</td>

				<td class="done">990</td>
				<td class="done">994</td>
				<td class="done">998</td>
				<td class="done">978</td>
				<td class="done">993</td>
			</tr>

			<tr class="line">
				<td>2</td>
				<td class="team">Tykadla</td>
				<td>29664</td>
				<td>
					4000
				</td>
				<td>
					90
				</td>

				<td class="done">994</td>
				<td class="done">993</td>
				<td class="empty">X</td>
				<td class="done">995</td>
				<td class="done">991</td>
				<td class="done">981</td>

				<td class="done">999</td>
				<td class="done">995</td>
				<td class="done">974</td>
				<td class="done">998</td>
				<td class="done">992</td>
				<td class="done">981</td>

				<td class="done">989</td>
				<td class="done">999</td>
				<td class="done">1000</td>
				<td class="done">997</td>
				<td class="done">995</td>
				<td class="done">989</td>

				<td class="done">986</td>
				<td class="done">984</td>
				<td class="done">993</td>
				<td class="done">979</td>
				<td class="done">998</td>
				<td class="done">985</td>

				<td class="done">989</td>
				<td class="done">980</td>
				<td class="done">998</td>
			</tr>
			<tr class="line">
				<td>3</td>
				<td class="team">Kokokel</td>

				<td>29602</td>
				<td>
					4000
				</td>
				<td>
					100
				</td>
				<td class="done">997</td>
				<td class="done">999</td>

				<td class="empty">X</td>
				<td class="done">999</td>
				<td class="done">995</td>
				<td class="done">994</td>
				<td class="done">987</td>
				<td class="done">993</td>

				<td class="done">992</td>
				<td class="done">993</td>
				<td class="done">980</td>
				<td class="done">978</td>
				<td class="done">995</td>
				<td class="done">975</td>

				<td class="done">993</td>
				<td class="done">1000</td>
				<td class="done">993</td>
				<td class="done">971</td>
				<td class="done">990</td>
				<td class="done">982</td>

				<td class="done">980</td>
				<td class="done">998</td>
				<td class="done">980</td>
				<td class="done">999</td>
				<td class="done">994</td>
				<td class="done">957</td>

				<td class="done">988</td>
			</tr>
			<tr class="line">
				<td>4</td>
				<td class="team">Cinquecento</td>
				<td>28398</td>
				<td>
					4000
				</td>

				<td>
					90
				</td>
				<td class="done">992</td>
				<td class="done">982</td>
				<td class="empty">X</td>
				<td class="done">998</td>

				<td class="done">950</td>
				<td class="done">978</td>
				<td class="done">997</td>
				<td class="done">985</td>
				<td class="done">968</td>
				<td class="done">985</td>

				<td class="done">974</td>
				<td class="done">976</td>
				<td class="done">993</td>
				<td class="done">969</td>
				<td class="done">982</td>
				<td class="done">994</td>

				<td class="done">986</td>
				<td class="done">964</td>
				<td class="done">988</td>
				<td class="empty">X</td>
				<td class="done">976</td>
				<td class="done">985</td>

				<td class="done">948</td>
				<td class="done">980</td>
				<td class="done">974</td>
				<td class="done">994</td>
				<td class="done">970</td>
			</tr>

			<tr class="line">
				<td>5</td>
				<td class="team">IQtIQ</td>
				<td>28226</td>
				<td>
					4000
				</td>
				<td>
					490
				</td>

				<td class="done">993</td>
				<td class="done">992</td>
				<td class="done">996</td>
				<td class="done">993</td>
				<td class="done">984</td>
				<td class="done">989</td>

				<td class="done">990</td>
				<td class="done">994</td>
				<td class="done">982</td>
				<td class="done">980</td>
				<td class="done">981</td>
				<td class="done">1000</td>

				<td class="done">996</td>
				<td class="done">977</td>
				<td class="done">990</td>
				<td class="empty">X</td>
				<td class="done">999</td>
				<td class="done">991</td>

				<td class="done">982</td>
				<td class="empty">X</td>
				<td class="done">991</td>
				<td class="done">996</td>
				<td class="done">991</td>
				<td class="done">991</td>

				<td class="done">984</td>
				<td class="done">991</td>
				<td class="done">963</td>
			</tr>
			<tr class="line">
				<td>6</td>
				<td class="team">Matfyzák a matfyzák, a.s.</td>

				<td>27084</td>
				<td>
					3500
				</td>
				<td>
					40
				</td>
				<td class="done">987</td>
				<td class="done">950</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">999</td>
				<td class="done">999</td>
				<td class="done">998</td>
				<td class="done">962</td>

				<td class="done">959</td>
				<td class="done">997</td>
				<td class="done">994</td>
				<td class="done">984</td>
				<td class="empty">X</td>
				<td class="done">960</td>

				<td class="done">986</td>
				<td class="done">992</td>
				<td class="done">987</td>
				<td class="done">976</td>
				<td class="done">994</td>
				<td class="done">983</td>

				<td class="done">994</td>
				<td class="done">999</td>
				<td class="done">994</td>
				<td class="done">986</td>
				<td class="done">993</td>
				<td class="done">964</td>

				<td class="done">987</td>
			</tr>
			<tr class="line">
				<td>7</td>
				<td class="team">Прагоры</td>
				<td>27013</td>
				<td>
					3500
				</td>

				<td>
					130
				</td>
				<td class="done">995</td>
				<td class="done">969</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">987</td>
				<td class="done">987</td>
				<td class="done">993</td>
				<td class="done">968</td>
				<td class="done">979</td>
				<td class="done">996</td>

				<td class="done">985</td>
				<td class="done">975</td>
				<td class="done">991</td>
				<td class="done">980</td>
				<td class="empty">X</td>
				<td class="done">996</td>

				<td class="done">990</td>
				<td class="done">996</td>
				<td class="done">1000</td>
				<td class="done">980</td>
				<td class="done">984</td>
				<td class="done">995</td>

				<td class="done">974</td>
				<td class="done">969</td>
				<td class="done">991</td>
				<td class="done">989</td>
				<td class="done">974</td>
			</tr>

			<tr class="line">
				<td>8</td>
				<td class="team">kancl</td>
				<td>26906</td>
				<td>
					3500
				</td>
				<td>
					140
				</td>

				<td class="done">978</td>
				<td class="done">980</td>
				<td class="empty">X</td>
				<td class="done">994</td>
				<td class="done">979</td>
				<td class="done">997</td>

				<td class="done">996</td>
				<td class="done">970</td>
				<td class="done">962</td>
				<td class="done">991</td>
				<td class="done">976</td>
				<td class="done">970</td>

				<td class="done">1000</td>
				<td class="done">955</td>
				<td class="done">979</td>
				<td class="done">998</td>
				<td class="empty">X</td>
				<td class="done">985</td>

				<td class="done">996</td>
				<td class="empty">X</td>
				<td class="done">979</td>
				<td class="done">992</td>
				<td class="done">982</td>
				<td class="done">975</td>

				<td class="done">996</td>
				<td class="done">954</td>
				<td class="done">962</td>
			</tr>
			<tr class="line">
				<td>9</td>
				<td class="team">Societas Leptonychotes</td>

				<td>26084</td>
				<td>
					3500
				</td>
				<td>
					160
				</td>
				<td class="done">985</td>
				<td class="done">968</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">990</td>
				<td class="done">973</td>
				<td class="empty">X</td>
				<td class="done">998</td>

				<td class="done">989</td>
				<td class="done">990</td>
				<td class="done">968</td>
				<td class="done">992</td>
				<td class="done">998</td>
				<td class="empty">X</td>

				<td class="done">985</td>
				<td class="done">995</td>
				<td class="done">989</td>
				<td class="done">993</td>
				<td class="done">995</td>
				<td class="done">995</td>

				<td class="done">996</td>
				<td class="done">993</td>
				<td class="done">988</td>
				<td class="done">995</td>
				<td class="done">997</td>
				<td class="done">975</td>

				<td class="done">997</td>
			</tr>
			<tr class="line">
				<td>10</td>
				<td class="team">Sloniky</td>
				<td>24389</td>
				<td>
					3000
				</td>

				<td>
					90
				</td>
				<td class="done">998</td>
				<td class="done">953</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">966</td>
				<td class="done">956</td>
				<td class="empty">X</td>
				<td class="done">961</td>
				<td class="done">948</td>
				<td class="done">983</td>

				<td class="done">977</td>
				<td class="done">983</td>
				<td class="empty">X</td>
				<td class="done">964</td>
				<td class="empty">X</td>
				<td class="done">993</td>

				<td class="done">992</td>
				<td class="done">992</td>
				<td class="done">977</td>
				<td class="done">997</td>
				<td class="done">987</td>
				<td class="done">983</td>

				<td class="done">967</td>
				<td class="done">993</td>
				<td class="done">967</td>
				<td class="done">962</td>
				<td class="done">980</td>
			</tr>

			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
				<th>P1</th>

				<th>L1</th>
				<th>S1</th>
				<th>P2</th>
				<th>L2</th>
				<th>S2</th>
				<th>P3</th>

				<th>L3</th>
				<th>S3</th>
				<th>P4</th>
				<th>L4</th>
				<th>S4</th>
				<th>P5</th>

				<th>L5</th>
				<th>S5</th>
				<th>P6</th>
				<th>L6</th>
				<th>S6</th>
				<th>P7</th>

				<th>L7</th>
				<th>S7</th>
				<th>P8</th>
				<th>L8</th>
				<th>S8</th>
				<th>P9</th>

				<th>L9</th>
				<th>S9</th>
			</tr>
			<tr>
				<td>11</td>
				<td class="team">Red Alert</td>
				<td>23482</td>

				<td>
					3000
				</td>
				<td>
					60
				</td>
				<td class="done">988</td>
				<td class="done">949</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">978</td>
				<td class="done">971</td>
				<td class="done">992</td>
				<td class="done">984</td>
				<td class="done">969</td>

				<td class="done">971</td>
				<td class="done">972</td>
				<td class="empty">X</td>
				<td class="done">990</td>
				<td class="done">996</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">973</td>
				<td class="done">984</td>
				<td class="done">979</td>
				<td class="done">1000</td>

				<td class="done">982</td>
				<td class="done">950</td>
				<td class="done">988</td>
				<td class="done">980</td>
				<td class="done">963</td>
				<td class="done">983</td>

			</tr>
			<tr class="line">
				<td>12</td>
				<td class="team">MY</td>
				<td>23412</td>
				<td>
					2000
				</td>
				<td>

					80
				</td>
				<td class="empty">X</td>
				<td class="done">975</td>
				<td class="done">999</td>
				<td class="empty">X</td>
				<td class="done">972</td>

				<td class="done">957</td>
				<td class="empty">X</td>
				<td class="done">978</td>
				<td class="done">964</td>
				<td class="done">967</td>
				<td class="done">986</td>

				<td class="done">980</td>
				<td class="empty">X</td>
				<td class="done">997</td>
				<td class="done">981</td>
				<td class="empty">X</td>
				<td class="done">996</td>

				<td class="done">965</td>
				<td class="done">973</td>
				<td class="done">989</td>
				<td class="done">998</td>
				<td class="done">994</td>
				<td class="done">981</td>

				<td class="done">957</td>
				<td class="done">965</td>
				<td class="done">967</td>
				<td class="done">951</td>
			</tr>
			<tr class="line">
				<td>13</td>

				<td class="team">Trosecnici</td>
				<td>23340</td>
				<td>
					3000
				</td>
				<td>
					170
				</td>
				<td class="done">983</td>

				<td class="done">951</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">960</td>
				<td class="done">963</td>
				<td class="done">991</td>

				<td class="empty">X</td>
				<td class="done">951</td>
				<td class="done">988</td>
				<td class="done">962</td>
				<td class="done">972</td>
				<td class="empty">X</td>

				<td class="done">986</td>
				<td class="done">999</td>
				<td class="empty">X</td>
				<td class="done">985</td>
				<td class="done">963</td>
				<td class="done">992</td>

				<td class="empty">X</td>
				<td class="done">986</td>
				<td class="done">991</td>
				<td class="done">978</td>
				<td class="done">977</td>
				<td class="done">999</td>

				<td class="done">981</td>
				<td class="done">952</td>
			</tr>
			<tr class="line">
				<td>14</td>
				<td class="team">Byli jsme čtyři</td>
				<td>21975</td>

				<td>
					1500
				</td>
				<td>
					160
				</td>
				<td class="done">979</td>
				<td class="done">995</td>
				<td class="done">994</td>

				<td class="empty">X</td>
				<td class="done">996</td>
				<td class="done">965</td>
				<td class="empty">X</td>
				<td class="done">964</td>
				<td class="done">994</td>

				<td class="done">979</td>
				<td class="done">990</td>
				<td class="done">964</td>
				<td class="empty">X</td>
				<td class="done">982</td>
				<td class="done">997</td>

				<td class="empty">X</td>
				<td class="done">997</td>
				<td class="done">987</td>
				<td class="empty">X</td>
				<td class="done">988</td>
				<td class="done">985</td>

				<td class="done">970</td>
				<td class="done">989</td>
				<td class="done">940</td>
				<td class="empty">X</td>
				<td class="done">990</td>
				<td class="done">990</td>

			</tr>
			<tr class="line">
				<td>15</td>
				<td class="team">My nic - to samo</td>
				<td>21151</td>
				<td>
					2500
				</td>
				<td>

					100
				</td>
				<td class="empty">X</td>
				<td class="done">991</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">970</td>

				<td class="done">996</td>
				<td class="done">994</td>
				<td class="done">992</td>
				<td class="done">979</td>
				<td class="done">961</td>
				<td class="done">988</td>

				<td class="done">998</td>
				<td class="empty">X</td>
				<td class="done">978</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">999</td>
				<td class="done">989</td>
				<td class="empty">X</td>
				<td class="done">978</td>
				<td class="done">988</td>
				<td class="done">987</td>

				<td class="done">984</td>
				<td class="done">990</td>
				<td class="done">995</td>
				<td class="done">994</td>
			</tr>
			<tr class="line">
				<td>16</td>

				<td class="team">Tweety neni kura!!!</td>
				<td>20938</td>
				<td>
					2500
				</td>
				<td>
					60
				</td>
				<td class="empty">X</td>

				<td class="done">955</td>
				<td class="empty">X</td>
				<td class="done">997</td>
				<td class="done">967</td>
				<td class="done">960</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">958</td>
				<td class="done">965</td>
				<td class="done">963</td>
				<td class="done">966</td>
				<td class="empty">X</td>

				<td class="done">972</td>
				<td class="done">983</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">969</td>
				<td class="done">978</td>

				<td class="empty">X</td>
				<td class="done">990</td>
				<td class="done">978</td>
				<td class="done">985</td>
				<td class="done">989</td>
				<td class="done">969</td>

				<td class="done">972</td>
				<td class="done">982</td>
			</tr>
			<tr class="line">
				<td>17</td>
				<td class="team">žufouni</td>
				<td>20923</td>

				<td>
					2500
				</td>
				<td>
					40
				</td>
				<td class="empty">X</td>
				<td class="done">960</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">949</td>
				<td class="done">970</td>
				<td class="empty">X</td>
				<td class="done">963</td>
				<td class="done">956</td>

				<td class="done">982</td>
				<td class="empty">X</td>
				<td class="done">960</td>
				<td class="empty">X</td>
				<td class="done">959</td>
				<td class="done">998</td>

				<td class="done">991</td>
				<td class="empty">X</td>
				<td class="done">984</td>
				<td class="done">981</td>
				<td class="empty">X</td>
				<td class="done">974</td>

				<td class="done">980</td>
				<td class="done">962</td>
				<td class="done">974</td>
				<td class="done">986</td>
				<td class="done">970</td>
				<td class="done">964</td>

			</tr>
			<tr class="line">
				<td>18</td>
				<td class="team">Jak se nám líbí!</td>
				<td>20077</td>
				<td>
					2500
				</td>
				<td>

					30
				</td>
				<td class="empty">X</td>
				<td class="done">990</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">986</td>

				<td class="done">991</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">977</td>
				<td class="done">974</td>
				<td class="done">964</td>

				<td class="done">974</td>
				<td class="done">997</td>
				<td class="done">953</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">970</td>
				<td class="done">991</td>
				<td class="empty">X</td>
				<td class="done">988</td>
				<td class="done">972</td>
				<td class="done">961</td>

				<td class="done">982</td>
				<td class="done">983</td>
				<td class="done">965</td>
				<td class="done">989</td>
			</tr>
			<tr class="line">
				<td>19</td>

				<td class="team">KoKoDlDlSi</td>
				<td>20062</td>
				<td>
					2500
				</td>
				<td>
					140
				</td>
				<td class="empty">X</td>

				<td class="done">988</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">998</td>
				<td class="empty">X</td>
				<td class="done">989</td>

				<td class="done">991</td>
				<td class="done">994</td>
				<td class="done">992</td>
				<td class="done">1000</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">976</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">994</td>
				<td class="done">966</td>
				<td class="done">987</td>

				<td class="empty">X</td>
				<td class="done">960</td>
				<td class="done">977</td>
				<td class="done">975</td>
				<td class="done">963</td>
				<td class="done">968</td>

				<td class="done">985</td>
				<td class="done">999</td>
			</tr>
			<tr class="line">
				<td>20</td>
				<td class="team">Pokakaný dudlík</td>
				<td>19994</td>

				<td>
					1500
				</td>
				<td>
					40
				</td>
				<td class="empty">X</td>
				<td class="done">976</td>
				<td class="done">995</td>

				<td class="empty">X</td>
				<td class="done">975</td>
				<td class="done">976</td>
				<td class="empty">X</td>
				<td class="done">990</td>
				<td class="done">971</td>

				<td class="done">966</td>
				<td class="done">978</td>
				<td class="done">962</td>
				<td class="done">988</td>
				<td class="done">989</td>
				<td class="done">991</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">979</td>
				<td class="done">971</td>
				<td class="empty">X</td>
				<td class="done">977</td>

				<td class="empty">X</td>
				<td class="done">964</td>
				<td class="done">960</td>
				<td class="empty">X</td>
				<td class="done">953</td>
				<td class="done">973</td>

			</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>

				<th>P1</th>
				<th>L1</th>
				<th>S1</th>
				<th>P2</th>
				<th>L2</th>
				<th>S2</th>

				<th>P3</th>
				<th>L3</th>
				<th>S3</th>
				<th>P4</th>
				<th>L4</th>
				<th>S4</th>

				<th>P5</th>
				<th>L5</th>
				<th>S5</th>
				<th>P6</th>
				<th>L6</th>
				<th>S6</th>

				<th>P7</th>
				<th>L7</th>
				<th>S7</th>
				<th>P8</th>
				<th>L8</th>
				<th>S8</th>

				<th>P9</th>
				<th>L9</th>
				<th>S9</th>
			</tr>
			<tr>
				<td>21</td>
				<td class="team">Ztráty a nálezy</td>

				<td>19365</td>
				<td>
					2000
				</td>
				<td>
					190
				</td>
				<td class="done">989</td>
				<td class="done">964</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">974</td>
				<td class="done">975</td>
				<td class="empty">X</td>
				<td class="done">988</td>

				<td class="done">966</td>
				<td class="done">975</td>
				<td class="done">984</td>
				<td class="done">988</td>
				<td class="empty">X</td>
				<td class="done">985</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">995</td>
				<td class="done">976</td>
				<td class="empty">X</td>

				<td class="done">964</td>
				<td class="empty">X</td>
				<td class="done">983</td>
				<td class="done">938</td>
				<td class="done">981</td>
				<td class="done">992</td>

				<td class="done">938</td>
			</tr>
			<tr class="line">
				<td>22</td>
				<td class="team">Poklusem!</td>
				<td>19246</td>
				<td>
					500
				</td>

				<td>
					70
				</td>
				<td class="empty">X</td>
				<td class="done">979</td>
				<td class="done">998</td>
				<td class="empty">X</td>

				<td class="done">988</td>
				<td class="done">993</td>
				<td class="empty">X</td>
				<td class="done">996</td>
				<td class="done">984</td>
				<td class="done">984</td>

				<td class="done">979</td>
				<td class="done">999</td>
				<td class="empty">X</td>
				<td class="done">992</td>
				<td class="done">992</td>
				<td class="empty">X</td>

				<td class="done">998</td>
				<td class="done">990</td>
				<td class="empty">X</td>
				<td class="done">996</td>
				<td class="done">989</td>
				<td class="empty">X</td>

				<td class="done">995</td>
				<td class="done">998</td>
				<td class="empty">X</td>
				<td class="done">1000</td>
				<td class="done">966</td>
			</tr>

			<tr class="line">
				<td>23</td>
				<td class="team">Kings of Medlanky</td>
				<td>18527</td>
				<td>
					1000
				</td>
				<td>
					150
				</td>

				<td class="done">990</td>
				<td class="done">970</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">973</td>
				<td class="done">984</td>

				<td class="empty">X</td>
				<td class="done">989</td>
				<td class="done">964</td>
				<td class="empty">X</td>
				<td class="done">995</td>
				<td class="done">989</td>

				<td class="empty">X</td>
				<td class="done">988</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">1000</td>
				<td class="done">994</td>

				<td class="empty">X</td>
				<td class="done">1000</td>
				<td class="done">966</td>
				<td class="empty">X</td>
				<td class="done">997</td>
				<td class="done">964</td>

				<td class="done">962</td>
				<td class="done">993</td>
				<td class="done">959</td>
			</tr>
			<tr class="line">
				<td>24</td>
				<td class="team">Privat Members</td>

				<td>18159</td>
				<td>
					1500
				</td>
				<td>
					60
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">1000</td>
				<td class="done">966</td>
				<td class="empty">X</td>
				<td class="done">1000</td>

				<td class="done">996</td>
				<td class="done">963</td>
				<td class="empty">X</td>
				<td class="done">993</td>
				<td class="done">999</td>
				<td class="done">983</td>

				<td class="done">978</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">967</td>
				<td class="empty">X</td>
				<td class="done">994</td>

				<td class="done">973</td>
				<td class="empty">X</td>
				<td class="done">951</td>
				<td class="done">987</td>
				<td class="done">992</td>
				<td class="done">999</td>

				<td class="done">978</td>
			</tr>
			<tr class="line">
				<td>25</td>
				<td class="team">Faltus Team</td>
				<td>18063</td>
				<td>
					1500
				</td>

				<td>
					80
				</td>
				<td class="empty">X</td>
				<td class="done">977</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">992</td>
				<td class="done">962</td>
				<td class="done">995</td>
				<td class="done">982</td>
				<td class="done">991</td>
				<td class="done">981</td>

				<td class="done">993</td>
				<td class="done">957</td>
				<td class="empty">X</td>
				<td class="done">950</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">988</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">975</td>
				<td class="done">975</td>

				<td class="done">992</td>
				<td class="done">983</td>
				<td class="empty">X</td>
				<td class="done">979</td>
				<td class="done">971</td>
			</tr>

			<tr class="line">
				<td>26</td>
				<td class="team">Červený trpaslík</td>
				<td>17134</td>
				<td>
					1500
				</td>
				<td>
					50
				</td>

				<td class="done">996</td>
				<td class="done">996</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">994</td>
				<td class="done">955</td>

				<td class="empty">X</td>
				<td class="done">997</td>
				<td class="done">991</td>
				<td class="done">994</td>
				<td class="done">961</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">988</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">962</td>

				<td class="done">975</td>
				<td class="empty">X</td>
				<td class="done">982</td>
				<td class="empty">X</td>
				<td class="done">986</td>
				<td class="done">981</td>

				<td class="empty">X</td>
				<td class="done">947</td>
				<td class="done">979</td>
			</tr>
			<tr class="line">
				<td>27</td>
				<td class="team">team13</td>

				<td>16693</td>
				<td>
					1000
				</td>
				<td>
					80
				</td>
				<td class="done">999</td>
				<td class="done">998</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">997</td>
				<td class="done">995</td>
				<td class="empty">X</td>
				<td class="done">976</td>

				<td class="done">995</td>
				<td class="done">976</td>
				<td class="done">996</td>
				<td class="done">955</td>
				<td class="empty">X</td>
				<td class="done">995</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">986</td>

				<td class="done">970</td>
				<td class="empty">X</td>
				<td class="done">973</td>
				<td class="done">965</td>
				<td class="empty">X</td>
				<td class="done">997</td>

				<td class="done">1000</td>
			</tr>
			<tr class="line">
				<td>28</td>
				<td class="team">Bystrí, silní, tvoriví</td>
				<td>15679</td>
				<td>
					1000
				</td>

				<td>
					130
				</td>
				<td class="done">1000</td>
				<td class="done">987</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">957</td>
				<td class="done">1000</td>
				<td class="empty">X</td>
				<td class="done">980</td>
				<td class="done">988</td>
				<td class="empty">X</td>

				<td class="done">973</td>
				<td class="done">995</td>
				<td class="empty">X</td>
				<td class="done">998</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">990</td>
				<td class="empty">X</td>
				<td class="done">986</td>

				<td class="done">999</td>
				<td class="done">992</td>
				<td class="empty">X</td>
				<td class="done">996</td>
				<td class="done">968</td>
			</tr>

			<tr class="line">
				<td>29</td>
				<td class="team">Řezníčci</td>
				<td>15540</td>
				<td>
					1000
				</td>
				<td>
					40
				</td>

				<td class="empty">X</td>
				<td class="done">961</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">969</td>
				<td class="done">972</td>

				<td class="empty">X</td>
				<td class="done">979</td>
				<td class="done">961</td>
				<td class="empty">X</td>
				<td class="done">967</td>
				<td class="done">990</td>

				<td class="empty">X</td>
				<td class="done">991</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">986</td>

				<td class="done">980</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">953</td>
				<td class="done">976</td>

				<td class="done">972</td>
				<td class="done">951</td>
				<td class="done">972</td>
			</tr>
			<tr class="line">
				<td>30</td>
				<td class="team">elfel</td>

				<td>15496</td>
				<td>
					2000
				</td>
				<td>
					100
				</td>
				<td class="empty">X</td>
				<td class="done">965</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">968</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">957</td>
				<td class="done">969</td>
				<td class="done">975</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">984</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">968</td>
				<td class="done">974</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">990</td>
				<td class="done">960</td>
				<td class="done">968</td>
				<td class="done">977</td>
				<td class="done">960</td>

				<td class="done">981</td>
			</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>

				<th>-</th>
				<th>P1</th>
				<th>L1</th>
				<th>S1</th>
				<th>P2</th>
				<th>L2</th>

				<th>S2</th>
				<th>P3</th>
				<th>L3</th>
				<th>S3</th>
				<th>P4</th>
				<th>L4</th>

				<th>S4</th>
				<th>P5</th>
				<th>L5</th>
				<th>S5</th>
				<th>P6</th>
				<th>L6</th>

				<th>S6</th>
				<th>P7</th>
				<th>L7</th>
				<th>S7</th>
				<th>P8</th>
				<th>L8</th>

				<th>S8</th>
				<th>P9</th>
				<th>L9</th>
				<th>S9</th>
			</tr>
			<tr>
				<td>31</td>

				<td class="team">LaMky</td>
				<td>15427</td>
				<td>
					1000
				</td>
				<td>
					180
				</td>
				<td class="done">976</td>

				<td class="done">958</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">981</td>
				<td class="done">977</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">942</td>
				<td class="done">964</td>
				<td class="empty">X</td>
				<td class="done">968</td>
				<td class="empty">X</td>

				<td class="done">970</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">972</td>
				<td class="empty">X</td>

				<td class="done">993</td>
				<td class="done">962</td>
				<td class="empty">X</td>
				<td class="done">996</td>
				<td class="done">970</td>
				<td class="empty">X</td>

				<td class="done">986</td>
				<td class="done">992</td>
			</tr>
			<tr class="line">
				<td>32</td>
				<td class="team">Geek Team</td>
				<td>15244</td>

				<td>
					2000
				</td>
				<td>
					400
				</td>
				<td class="done">980</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">971</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">977</td>
				<td class="done">946</td>

				<td class="done">995</td>
				<td class="empty">X</td>
				<td class="done">959</td>
				<td class="empty">X</td>
				<td class="done">952</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">988</td>
				<td class="empty">X</td>
				<td class="done">985</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">981</td>
				<td class="empty">X</td>
				<td class="done">962</td>
				<td class="done">995</td>
				<td class="done">976</td>
				<td class="done">977</td>

			</tr>
			<tr class="line">
				<td>33</td>
				<td class="team">Samotáři</td>
				<td>15221</td>
				<td>
					1000
				</td>
				<td>

					280
				</td>
				<td class="empty">X</td>
				<td class="done">984</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">959</td>

				<td class="done">974</td>
				<td class="empty">X</td>
				<td class="done">967</td>
				<td class="done">937</td>
				<td class="empty">X</td>
				<td class="done">999</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">961</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">985</td>
				<td class="done">967</td>
				<td class="done">971</td>
				<td class="done">976</td>

				<td class="done">951</td>
				<td class="done">963</td>
				<td class="done">959</td>
				<td class="done">948</td>
			</tr>
			<tr class="line">
				<td>34</td>

				<td class="team">AJETO</td>
				<td>15118</td>
				<td>
					500
				</td>
				<td>
					120
				</td>
				<td class="empty">X</td>

				<td class="done">973</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">990</td>
				<td class="done">992</td>
				<td class="empty">X</td>

				<td class="done">960</td>
				<td class="done">985</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">971</td>
				<td class="empty">X</td>

				<td class="done">968</td>
				<td class="done">989</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">982</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">992</td>
				<td class="empty">X</td>
				<td class="done">993</td>
				<td class="done">997</td>
				<td class="done">988</td>

				<td class="done">973</td>
				<td class="done">985</td>
			</tr>
			<tr class="line">
				<td>35</td>
				<td class="team">Botnik</td>
				<td>14851</td>

				<td>
					1500
				</td>
				<td>
					3300
				</td>
				<td class="empty">X</td>
				<td class="done">985</td>
				<td class="done">997</td>

				<td class="empty">X</td>
				<td class="done">977</td>
				<td class="empty">X</td>
				<td class="done">988</td>
				<td class="empty">X</td>
				<td class="done">945</td>

				<td class="empty">X</td>
				<td class="done">971</td>
				<td class="done">994</td>
				<td class="empty">X</td>
				<td class="done">967</td>
				<td class="done">987</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">999</td>
				<td class="done">959</td>

				<td class="done">989</td>
				<td class="done">984</td>
				<td class="done">979</td>
				<td class="done">982</td>
				<td class="done">988</td>
				<td class="done">960</td>

			</tr>
			<tr class="line">
				<td>36</td>
				<td class="team">Diamhra</td>
				<td>14573</td>
				<td>
					2000
				</td>
				<td>

					50
				</td>
				<td class="empty">X</td>
				<td class="done">986</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">983</td>

				<td class="done">964</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">986</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">971</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">997</td>
				<td class="empty">X</td>
				<td class="done">958</td>
				<td class="done">987</td>
				<td class="done">957</td>

				<td class="done">942</td>
				<td class="done">1000</td>
				<td class="done">955</td>
				<td class="done">937</td>
			</tr>
			<tr class="line">
				<td>37</td>

				<td class="team">Projížďka na střele</td>
				<td>14502</td>
				<td>
					1000
				</td>
				<td>
					160
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">993</td>
				<td class="empty">X</td>
				<td class="done">961</td>
				<td class="done">989</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">976</td>
				<td class="done">977</td>
				<td class="empty">X</td>
				<td class="done">996</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">977</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">998</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">972</td>
				<td class="done">969</td>
				<td class="done">968</td>
				<td class="done">967</td>
				<td class="empty">X</td>

				<td class="done">952</td>
				<td class="done">967</td>
			</tr>
			<tr class="line">
				<td>38</td>
				<td class="team">Posleda</td>
				<td>14021</td>

				<td>
					1500
				</td>
				<td>
					50
				</td>
				<td class="empty">X</td>
				<td class="done">974</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">985</td>
				<td class="done">986</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">938</td>

				<td class="done">989</td>
				<td class="empty">X</td>
				<td class="done">958</td>
				<td class="empty">X</td>
				<td class="done">962</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">972</td>
				<td class="empty">X</td>
				<td class="done">965</td>

				<td class="empty">X</td>
				<td class="done">965</td>
				<td class="done">959</td>
				<td class="done">978</td>
				<td class="empty">X</td>
				<td class="done">940</td>

			</tr>
			<tr class="line">
				<td>39</td>
				<td class="team">Havran</td>
				<td>13501</td>
				<td>
					0
				</td>
				<td>

					50
				</td>
				<td class="empty">X</td>
				<td class="done">1000</td>
				<td class="done">1000</td>
				<td class="empty">X</td>
				<td class="done">944</td>

				<td class="done">952</td>
				<td class="empty">X</td>
				<td class="done">973</td>
				<td class="done">954</td>
				<td class="empty">X</td>
				<td class="done">960</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">963</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">987</td>
				<td class="done">981</td>
				<td class="empty">X</td>
				<td class="done">963</td>

				<td class="done">952</td>
				<td class="empty">X</td>
				<td class="done">969</td>
				<td class="done">953</td>
			</tr>
			<tr class="line">
				<td>40</td>

				<td class="team">mlok</td>
				<td>13006</td>
				<td>
					1500
				</td>
				<td>
					70
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">941</td>
				<td class="done">967</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">936</td>
				<td class="done">987</td>
				<td class="done">997</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">957</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">993</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">974</td>
				<td class="done">944</td>
				<td class="empty">X</td>
				<td class="done">975</td>

				<td class="done">949</td>
				<td class="done">956</td>
			</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>

				<th>+</th>
				<th>-</th>
				<th>P1</th>
				<th>L1</th>
				<th>S1</th>
				<th>P2</th>

				<th>L2</th>
				<th>S2</th>
				<th>P3</th>
				<th>L3</th>
				<th>S3</th>
				<th>P4</th>

				<th>L4</th>
				<th>S4</th>
				<th>P5</th>
				<th>L5</th>
				<th>S5</th>
				<th>P6</th>

				<th>L6</th>
				<th>S6</th>
				<th>P7</th>
				<th>L7</th>
				<th>S7</th>
				<th>P8</th>

				<th>L8</th>
				<th>S8</th>
				<th>P9</th>
				<th>L9</th>
				<th>S9</th>
			</tr>

			<tr>
				<td>41</td>
				<td class="team">Koblížci</td>
				<td>12908</td>
				<td>
					500
				</td>
				<td>

					200
				</td>
				<td class="empty">X</td>
				<td class="done">963</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">956</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">974</td>
				<td class="done">949</td>
				<td class="done">962</td>
				<td class="done">998</td>

				<td class="done">973</td>
				<td class="empty">X</td>
				<td class="done">981</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">991</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">980</td>

				<td class="done">939</td>
				<td class="empty">X</td>
				<td class="done">987</td>
				<td class="done">955</td>
			</tr>
			<tr class="line">
				<td>42</td>

				<td class="team">Kapře, umři</td>
				<td>12718</td>
				<td>
					0
				</td>
				<td>
					80
				</td>
				<td class="empty">X</td>

				<td class="done">967</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">980</td>
				<td class="done">969</td>
				<td class="empty">X</td>

				<td class="done">965</td>
				<td class="done">973</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">996</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">997</td>
				<td class="empty">X</td>

				<td class="done">992</td>
				<td class="done">999</td>
				<td class="empty">X</td>
				<td class="done">966</td>
				<td class="done">1000</td>
				<td class="empty">X</td>

				<td class="done">998</td>
				<td class="done">996</td>
			</tr>
			<tr class="line">
				<td>43</td>
				<td class="team">para-N-methylaminoazobenzen</td>
				<td>12509</td>

				<td>
					0
				</td>
				<td>
					110
				</td>
				<td class="empty">X</td>
				<td class="done">997</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">982</td>
				<td class="done">983</td>
				<td class="empty">X</td>
				<td class="done">975</td>
				<td class="done">975</td>

				<td class="empty">X</td>
				<td class="done">958</td>
				<td class="done">991</td>
				<td class="empty">X</td>
				<td class="done">951</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">963</td>

				<td class="empty">X</td>
				<td class="done">971</td>
				<td class="done">941</td>
				<td class="empty">X</td>
				<td class="done">946</td>
				<td class="done">986</td>

			</tr>
			<tr class="line">
				<td>44</td>
				<td class="team">Dopplerův jev zapomněl heslo</td>
				<td>12435</td>
				<td>
					1000
				</td>
				<td>

					150
				</td>
				<td class="done">982</td>
				<td class="done">962</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">948</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">965</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">963</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">978</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">983</td>
				<td class="empty">X</td>
				<td class="done">949</td>

				<td class="done">955</td>
				<td class="done">985</td>
				<td class="done">950</td>
				<td class="done">965</td>
			</tr>
			<tr class="line">
				<td>45</td>

				<td class="team">Mažentoví Bústri</td>
				<td>11597</td>
				<td>
					1000
				</td>
				<td>
					90
				</td>
				<td class="empty">X</td>

				<td class="done">994</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">990</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">983</td>
				<td class="empty">X</td>
				<td class="done">987</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">983</td>

				<td class="empty">X</td>
				<td class="done">968</td>
				<td class="empty">X</td>
				<td class="done">959</td>
				<td class="done">954</td>
				<td class="done">970</td>

				<td class="done">942</td>
				<td class="done">957</td>
			</tr>
			<tr class="line">
				<td>46</td>
				<td class="team">interwin</td>
				<td>11464</td>

				<td>
					1000
				</td>
				<td>
					270
				</td>
				<td class="empty">X</td>
				<td class="done">954</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">993</td>
				<td class="done">982</td>
				<td class="empty">X</td>
				<td class="done">999</td>
				<td class="done">988</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">973</td>
				<td class="done">947</td>
				<td class="done">978</td>
				<td class="done">979</td>
				<td class="done">966</td>
				<td class="done">975</td>

			</tr>
			<tr class="line">
				<td>47</td>
				<td class="team">Supermuf</td>
				<td>11111</td>
				<td>
					500
				</td>
				<td>

					100
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">954</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">982</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">969</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">995</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">983</td>
				<td class="done">998</td>
				<td class="empty">X</td>
				<td class="done">995</td>
				<td class="empty">X</td>
				<td class="done">954</td>

				<td class="done">972</td>
				<td class="empty">X</td>
				<td class="done">948</td>
				<td class="done">961</td>
			</tr>
			<tr class="line">
				<td>48</td>

				<td class="team">GyTu Solvers</td>
				<td>11008</td>
				<td>
					500
				</td>
				<td>
					110
				</td>
				<td class="empty">X</td>

				<td class="done">952</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">945</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">959</td>
				<td class="done">997</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">982</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">971</td>
				<td class="done">997</td>
				<td class="done">946</td>
				<td class="done">949</td>
				<td class="empty">X</td>

				<td class="done">977</td>
				<td class="done">943</td>
			</tr>
			<tr class="line">
				<td>49</td>
				<td class="team">Šifrátoři</td>
				<td>10559</td>

				<td>
					1000
				</td>
				<td>
					30
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">954</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">955</td>

				<td class="done">973</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">954</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">981</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">952</td>
				<td class="done">961</td>
				<td class="done">961</td>
				<td class="done">944</td>
				<td class="done">954</td>

			</tr>
			<tr class="line">
				<td>50</td>
				<td class="team">poker face</td>
				<td>10321</td>
				<td>
					0
				</td>
				<td>

					330
				</td>
				<td class="empty">X</td>
				<td class="done">983</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">958</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">944</td>
				<td class="empty">X</td>
				<td class="done">989</td>

				<td class="done">985</td>
				<td class="empty">X</td>
				<td class="done">974</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">998</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">977</td>

				<td class="done">946</td>
				<td class="empty">X</td>
				<td class="done">958</td>
				<td class="done">939</td>
			</tr>
			<tr>
				<th>#</th>

				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
				<th>P1</th>
				<th>L1</th>

				<th>S1</th>
				<th>P2</th>
				<th>L2</th>
				<th>S2</th>
				<th>P3</th>
				<th>L3</th>

				<th>S3</th>
				<th>P4</th>
				<th>L4</th>
				<th>S4</th>
				<th>P5</th>
				<th>L5</th>

				<th>S5</th>
				<th>P6</th>
				<th>L6</th>
				<th>S6</th>
				<th>P7</th>
				<th>L7</th>

				<th>S7</th>
				<th>P8</th>
				<th>L8</th>
				<th>S8</th>
				<th>P9</th>
				<th>L9</th>

				<th>S9</th>
			</tr>
			<tr>
				<td>51</td>
				<td class="team">Genius proTeam !</td>
				<td>9931</td>
				<td>

					500
				</td>
				<td>
					330
				</td>
				<td class="empty">X</td>
				<td class="done">957</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">980</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">972</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">965</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">978</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">969</td>
				<td class="done">996</td>
				<td class="done">976</td>
				<td class="done">984</td>
				<td class="done">984</td>

			</tr>
			<tr class="line">
				<td>52</td>
				<td class="team">WeSwearSheWas18</td>
				<td>9910</td>
				<td>
					500
				</td>
				<td>

					270
				</td>
				<td class="empty">X</td>
				<td class="done">956</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">951</td>

				<td class="done">953</td>
				<td class="empty">X</td>
				<td class="done">986</td>
				<td class="done">1000</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">948</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">990</td>
				<td class="done">966</td>
				<td class="done">961</td>
				<td class="done">969</td>
			</tr>
			<tr class="line">
				<td>53</td>

				<td class="team">IT Arsenal</td>
				<td>9621</td>
				<td>
					1000
				</td>
				<td>
					50
				</td>
				<td class="done">986</td>

				<td class="done">989</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">947</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">970</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">984</td>
				<td class="done">945</td>
				<td class="done">973</td>
				<td class="empty">X</td>

				<td class="done">941</td>
				<td class="done">936</td>
			</tr>
			<tr class="line">
				<td>54</td>
				<td class="team">Zero power zero</td>
				<td>9595</td>

				<td>
					0
				</td>
				<td>
					130
				</td>
				<td class="empty">X</td>
				<td class="done">978</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">943</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">999</td>

				<td class="empty">X</td>
				<td class="done">982</td>
				<td class="done">987</td>
				<td class="empty">X</td>
				<td class="done">987</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">970</td>
				<td class="done">948</td>
				<td class="empty">X</td>
				<td class="done">982</td>
				<td class="done">949</td>

			</tr>
			<tr class="line">
				<td>55</td>
				<td class="team">Mamut břichem nahoru</td>
				<td>9240</td>
				<td>
					500
				</td>
				<td>

					40
				</td>
				<td class="done">984</td>
				<td class="done">981</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">983</td>
				<td class="done">943</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">986</td>
				<td class="empty">X</td>
				<td class="done">1000</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">1000</td>

				<td class="done">956</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">947</td>
			</tr>
			<tr class="line">
				<td>56</td>

				<td class="team">Sněhurka a.s.</td>
				<td>9179</td>
				<td>
					500
				</td>
				<td>
					20
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">962</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">980</td>
				<td class="done">968</td>
				<td class="done">969</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">993</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">975</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">958</td>
				<td class="done">950</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">944</td>
			</tr>
			<tr class="line">
				<td>57</td>
				<td class="team">Acervus aren</td>
				<td>8667</td>

				<td>
					0
				</td>
				<td>
					90
				</td>
				<td class="empty">X</td>
				<td class="done">971</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">972</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">983</td>
				<td class="done">979</td>
				<td class="empty">X</td>
				<td class="done">966</td>
				<td class="done">994</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">956</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">945</td>
				<td class="done">991</td>

			</tr>
			<tr class="line">
				<td>58</td>
				<td class="team">Pšeníci</td>
				<td>8658</td>
				<td>
					1000
				</td>
				<td>

					50
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">953</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">969</td>
				<td class="done">952</td>
				<td class="done">972</td>
				<td class="done">966</td>

				<td class="done">956</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">976</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">964</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>59</td>

				<td class="team">mechanický pomeranč</td>
				<td>8616</td>
				<td>
					0
				</td>
				<td>
					100
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">964</td>
				<td class="done">968</td>
				<td class="empty">X</td>

				<td class="done">971</td>
				<td class="done">953</td>
				<td class="empty">X</td>
				<td class="done">965</td>
				<td class="done">967</td>
				<td class="empty">X</td>

				<td class="done">990</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">980</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">958</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>60</td>
				<td class="team">Home alone</td>
				<td>8562</td>

				<td>
					1000
				</td>
				<td>
					170
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">947</td>

				<td class="done">978</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">956</td>
				<td class="done">980</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">979</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">971</td>
				<td class="done">971</td>
				<td class="done">950</td>

			</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>

				<th>P1</th>
				<th>L1</th>
				<th>S1</th>
				<th>P2</th>
				<th>L2</th>
				<th>S2</th>

				<th>P3</th>
				<th>L3</th>
				<th>S3</th>
				<th>P4</th>
				<th>L4</th>
				<th>S4</th>

				<th>P5</th>
				<th>L5</th>
				<th>S5</th>
				<th>P6</th>
				<th>L6</th>
				<th>S6</th>

				<th>P7</th>
				<th>L7</th>
				<th>S7</th>
				<th>P8</th>
				<th>L8</th>
				<th>S8</th>

				<th>P9</th>
				<th>L9</th>
				<th>S9</th>
			</tr>
			<tr>
				<td>61</td>
				<td class="team">lAsenzio</td>

				<td>7764</td>
				<td>
					1000
				</td>
				<td>
					60
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">942</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">960</td>
				<td class="done">1000</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">966</td>
				<td class="done">987</td>
				<td class="done">974</td>

				<td class="done">995</td>
			</tr>
			<tr class="line">
				<td>62</td>
				<td class="team">šneci</td>
				<td>7658</td>
				<td>
					0
				</td>

				<td>
					10
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">939</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">958</td>
				<td class="done">941</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">977</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">969</td>
				<td class="empty">X</td>

				<td class="done">955</td>
				<td class="done">971</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">958</td>
			</tr>

			<tr class="line">
				<td>63</td>
				<td class="team">Die Kryptografieren</td>
				<td>7650</td>
				<td>
					0
				</td>
				<td>
					70
				</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">965</td>
				<td class="done">961</td>

				<td class="empty">X</td>
				<td class="done">981</td>
				<td class="done">950</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">994</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">944</td>

				<td class="empty">X</td>
				<td class="done">983</td>
				<td class="done">942</td>
			</tr>
			<tr class="line">
				<td>64</td>
				<td class="team">Heuréka</td>

				<td>7624</td>
				<td>
					0
				</td>
				<td>
					40
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">955</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">939</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">979</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">974</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">961</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">943</td>
				<td class="empty">X</td>
				<td class="done">968</td>

				<td class="done">945</td>
			</tr>
			<tr class="line">
				<td>65</td>
				<td class="team">podmnozina</td>
				<td>6740</td>
				<td>
					0
				</td>

				<td>
					20
				</td>
				<td class="empty">X</td>
				<td class="done">972</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">952</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">966</td>
				<td class="empty">X</td>
				<td class="done">970</td>

				<td class="done">959</td>
				<td class="empty">X</td>
				<td class="done">992</td>
				<td class="done">949</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>

			<tr class="line">
				<td>66</td>
				<td class="team">Ustafaci</td>
				<td>6284</td>
				<td>
					500
				</td>
				<td>
					80
				</td>

				<td class="done">981</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">998</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">970</td>
				<td class="done">977</td>

				<td class="empty">X</td>
				<td class="done">965</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">973</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>67</td>
				<td class="team">M&amp;M CM&amp;HP</td>

				<td>5678</td>
				<td>
					0
				</td>
				<td>
					80
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">940</td>
				<td class="done">958</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">986</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">977</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">956</td>

				<td class="done">941</td>
			</tr>
			<tr class="line">
				<td>68</td>
				<td class="team">yxo</td>
				<td>5320</td>
				<td>
					500
				</td>

				<td>
					10
				</td>
				<td class="empty">X</td>
				<td class="done">959</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">979</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">961</td>
				<td class="empty">X</td>
				<td class="done">958</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">973</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>

			<tr class="line">
				<td>69</td>
				<td class="team">Bender of Brains</td>
				<td>3779</td>
				<td>
					0
				</td>
				<td>
					50
				</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">963</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">947</td>

				<td class="empty">X</td>
				<td class="done">943</td>
				<td class="done">976</td>
			</tr>
			<tr class="line">
				<td>70</td>
				<td class="team">JeNoMeZ</td>

				<td>3767</td>
				<td>
					0
				</td>
				<td>
					20
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">959</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">940</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">953</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">935</td>
			</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>

				<th>-</th>
				<th>P1</th>
				<th>L1</th>
				<th>S1</th>
				<th>P2</th>
				<th>L2</th>

				<th>S2</th>
				<th>P3</th>
				<th>L3</th>
				<th>S3</th>
				<th>P4</th>
				<th>L4</th>

				<th>S4</th>
				<th>P5</th>
				<th>L5</th>
				<th>S5</th>
				<th>P6</th>
				<th>L6</th>

				<th>S6</th>
				<th>P7</th>
				<th>L7</th>
				<th>S7</th>
				<th>P8</th>
				<th>L8</th>

				<th>S8</th>
				<th>P9</th>
				<th>L9</th>
				<th>S9</th>
			</tr>
			<tr>
				<td>71</td>

				<td class="team">1.FC Brno</td>
				<td>2818</td>
				<td>
					0
				</td>
				<td>
					40
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">967</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">945</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="done">946</td>
			</tr>
			<tr class="line">
				<td>72</td>
				<td class="team">Oto</td>
				<td>1957</td>

				<td>
					0
				</td>
				<td>
					30
				</td>
				<td class="done">991</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="done">996</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

			</tr>
			<tr class="line">
				<td>73</td>
				<td class="team">Vosaři</td>
				<td>916</td>
				<td>
					0
				</td>
				<td>

					30
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="done">946</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>74</td>

				<td class="team">Unterwasserman</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>75</td>
				<td class="team">Dršťkový Havran Masového Kašpárka</td>
				<td>0</td>

				<td>
					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

			</tr>
			<tr class="line">
				<td>76</td>
				<td class="team">defekt</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>

					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>77</td>

				<td class="team">GraMLy</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>78</td>
				<td class="team">EB</td>
				<td>0</td>

				<td>
					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

			</tr>
			<tr class="line">
				<td>79</td>
				<td class="team">Proč ne 32</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>

					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>80</td>

				<td class="team">J.U.P.</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>

				<th>+</th>
				<th>-</th>
				<th>P1</th>
				<th>L1</th>
				<th>S1</th>
				<th>P2</th>

				<th>L2</th>
				<th>S2</th>
				<th>P3</th>
				<th>L3</th>
				<th>S3</th>
				<th>P4</th>

				<th>L4</th>
				<th>S4</th>
				<th>P5</th>
				<th>L5</th>
				<th>S5</th>
				<th>P6</th>

				<th>L6</th>
				<th>S6</th>
				<th>P7</th>
				<th>L7</th>
				<th>S7</th>
				<th>P8</th>

				<th>L8</th>
				<th>S8</th>
				<th>P9</th>
				<th>L9</th>
				<th>S9</th>
			</tr>

			<tr>
				<td>81</td>
				<td class="team">Dopplerův jev</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>

					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>82</td>

				<td class="team">DEPHi</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>83</td>
				<td class="team">Já sám</td>
				<td>0</td>

				<td>
					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

			</tr>
			<tr class="line">
				<td>84</td>
				<td class="team">Stargate-Atlantis</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>

					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>85</td>

				<td class="team">špína</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>86</td>
				<td class="team">praskl řemen</td>
				<td>0</td>

				<td>
					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

			</tr>
			<tr class="line">
				<td>87</td>
				<td class="team">Proč ne 33</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>

					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>88</td>

				<td class="team">Rychlá hmota</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>89</td>
				<td class="team">Sila</td>
				<td>0</td>

				<td>
					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

			</tr>
			<tr class="line">
				<td>90</td>
				<td class="team">Without Logic</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>

					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr>
				<th>#</th>

				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
				<th>P1</th>
				<th>L1</th>

				<th>S1</th>
				<th>P2</th>
				<th>L2</th>
				<th>S2</th>
				<th>P3</th>
				<th>L3</th>

				<th>S3</th>
				<th>P4</th>
				<th>L4</th>
				<th>S4</th>
				<th>P5</th>
				<th>L5</th>

				<th>S5</th>
				<th>P6</th>
				<th>L6</th>
				<th>S6</th>
				<th>P7</th>
				<th>L7</th>

				<th>S7</th>
				<th>P8</th>
				<th>L8</th>
				<th>S8</th>
				<th>P9</th>
				<th>L9</th>

				<th>S9</th>
			</tr>
			<tr>
				<td>91</td>
				<td class="team">NeTým</td>
				<td>0</td>
				<td>

					0
				</td>
				<td>
					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

			</tr>
			<tr class="line">
				<td>92</td>
				<td class="team">PePa</td>
				<td>0</td>
				<td>
					0
				</td>
				<td>

					0
				</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
			<tr class="line">
				<td>93</td>

				<td class="team">Organizátoři</td>
				<td>-40</td>
				<td>
					0
				</td>
				<td>
					40
				</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>
				<td class="empty">X</td>

				<td class="empty">X</td>
				<td class="empty">X</td>
			</tr>
		</table>
{/block}
