{extends ../layout.phtml}
{block #body}
	<table id="score-stats" cellspacing="0">
			<tr>

				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
					<th>P1</th>

					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>
					<th>S1</th>

					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>
					<th>L4</th>

					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>
					<th>P7</th>

					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>
					<th>S7</th>

					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>1</td>
			<td class="team">voy-a-ger</td>
			<td>

					29686
			</td>
			<td>
					4000
			</td>
			<td>
					80
			</td>
					<td class="done">988</td>
					<td class="done">993</td>

					<td class="done">977</td>
					<td class="done">989</td>
					<td class="done">995</td>
					<td class="done">995</td>
					<td class="done">1000</td>
					<td class="done">993</td>

					<td class="done">980</td>
					<td class="done">995</td>
					<td class="done">996</td>
					<td class="done">988</td>
					<td class="done">970</td>
					<td class="done">994</td>

					<td class="done">991</td>
					<td class="done">999</td>
					<td class="done">969</td>
					<td class="done">999</td>
					<td class="done">999</td>
					<td class="done">1000</td>

					<td class="done">992</td>
					<td class="done">995</td>
					<td class="done">1000</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="done">998</td>

					<td class="done">1000</td>
		</tr>
			<tr class="line">
			<td>2</td>
			<td class="team">Tykadla</td>
			<td>
					29451
			</td>

			<td>
					4000
			</td>
			<td>
					100
			</td>
					<td class="done">980</td>
					<td class="done">991</td>
					<td class="done">985</td>

					<td class="done">996</td>
					<td class="done">972</td>
					<td class="done">944</td>
					<td class="done">998</td>
					<td class="done">998</td>
					<td class="done">996</td>

					<td class="done">998</td>
					<td class="done">995</td>
					<td class="done">958</td>
					<td class="done">1000</td>
					<td class="done">988</td>
					<td class="done">982</td>

					<td class="done">983</td>
					<td class="done">980</td>
					<td class="done">956</td>
					<td class="done">990</td>
					<td class="done">997</td>
					<td class="done">986</td>

					<td class="done">981</td>
					<td class="done">961</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="done">976</td>

		</tr>
			<tr class="line">
			<td>3</td>
			<td class="team">Pomocná škola</td>
			<td>
					28046
			</td>
			<td>

					3500
			</td>
			<td>
					70
			</td>
					<td class="done">1000</td>
					<td class="done">1000</td>
					<td class="done">988</td>

					<td class="done">970</td>
					<td class="done">981</td>
					<td class="done">961</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="done">959</td>

					<td class="done">997</td>
					<td class="done">1000</td>
					<td class="done">1000</td>
					<td class="done">946</td>
					<td class="done">995</td>
					<td class="done">985</td>

					<td class="done">996</td>
					<td class="done">987</td>
					<td class="done">963</td>
					<td class="done">1000</td>
					<td class="done">995</td>
					<td class="done">994</td>

					<td class="done">989</td>
					<td class="done">980</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">993</td>

		</tr>
			<tr class="line">
			<td>4</td>
			<td class="team">Jeníčci</td>
			<td>
					25929
			</td>
			<td>

					3500
			</td>
			<td>
					100
			</td>
					<td class="done">984</td>
					<td class="done">990</td>
					<td class="done">991</td>

					<td class="done">951</td>
					<td class="done">971</td>
					<td class="done">971</td>
					<td class="done">981</td>
					<td class="done">1000</td>
					<td class="done">994</td>

					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">980</td>
					<td class="done">944</td>
					<td class="done">982</td>
					<td class="done">978</td>

					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="done">995</td>
					<td class="done">983</td>
					<td class="done">985</td>

					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">985</td>

		</tr>
			<tr class="line">
			<td>5</td>
			<td class="team">Přizdisráči</td>
			<td>
					25111
			</td>
			<td>

					3500
			</td>
			<td>
					110
			</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">997</td>

					<td class="done">997</td>
					<td class="done">976</td>
					<td class="done">943</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">990</td>

					<td class="done">994</td>
					<td class="done">991</td>
					<td class="done">975</td>
					<td class="done">972</td>
					<td class="done">999</td>
					<td class="done">996</td>

					<td class="done">1000</td>
					<td class="done">974</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">999</td>

					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">982</td>

		</tr>
			<tr class="line">
			<td>6</td>
			<td class="team">Chce to nápad</td>
			<td>
					24981
			</td>
			<td>

					3500
			</td>
			<td>
					260
			</td>
					<td class="done">983</td>
					<td class="done">989</td>
					<td class="done">999</td>

					<td class="done">968</td>
					<td class="done">991</td>
					<td class="done">978</td>
					<td class="done">999</td>
					<td class="empty">X</td>
					<td class="done">998</td>

					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">998</td>
					<td class="done">965</td>
					<td class="done">983</td>
					<td class="done">988</td>

					<td class="done">978</td>
					<td class="done">986</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">990</td>

					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">999</td>

		</tr>
			<tr class="line">
			<td>7</td>
			<td class="team">nechci-uvest</td>
			<td>
					24537
			</td>
			<td>

					3000
			</td>
			<td>
					80
			</td>
					<td class="done">992</td>
					<td class="done">982</td>
					<td class="done">986</td>

					<td class="done">960</td>
					<td class="done">973</td>
					<td class="done">987</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="done">965</td>

					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="done">986</td>
					<td class="done">991</td>
					<td class="done">994</td>

					<td class="done">991</td>
					<td class="done">991</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="done">988</td>

					<td class="done">980</td>
					<td class="done">971</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>8</td>
			<td class="team">Ešte sa dohodneme</td>
			<td>
					23538
			</td>
			<td>

					3000
			</td>
			<td>
					40
			</td>
					<td class="done">991</td>
					<td class="done">985</td>
					<td class="empty">X</td>

					<td class="done">993</td>
					<td class="done">968</td>
					<td class="done">985</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="done">974</td>

					<td class="done">1000</td>
					<td class="done">994</td>
					<td class="done">967</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="done">960</td>

					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">947</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="done">995</td>

					<td class="done">976</td>
					<td class="done">995</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="done">990</td>

		</tr>
			<tr class="line">
			<td>9</td>
			<td class="team">Pařížská modrá</td>
			<td>
					23454
			</td>
			<td>

					3000
			</td>
			<td>
					40
			</td>
					<td class="done">965</td>
					<td class="done">996</td>
					<td class="done">975</td>

					<td class="done">941</td>
					<td class="done">987</td>
					<td class="done">982</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="done">972</td>

					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">976</td>
					<td class="done">963</td>
					<td class="done">992</td>
					<td class="done">956</td>

					<td class="done">992</td>
					<td class="done">999</td>
					<td class="done">950</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">978</td>

					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">947</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>

		</tr>
			<tr class="line">
			<td>10</td>
			<td class="team">kancl</td>
			<td>
					22088
			</td>
			<td>

					2500
			</td>
			<td>
					80
			</td>
					<td class="done">960</td>
					<td class="done">998</td>
					<td class="empty">X</td>

					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">969</td>

					<td class="done">999</td>
					<td class="done">993</td>
					<td class="done">971</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="done">984</td>

					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="done">998</td>
					<td class="done">999</td>
					<td class="done">983</td>

					<td class="done">983</td>
					<td class="done">959</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="empty">X</td>

		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>

					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>

					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>

					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>

					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>

					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>11</td>
			<td class="team">supermuf</td>

			<td>
					22084
			</td>
			<td>
					2500
			</td>
			<td>
					60
			</td>
					<td class="done">990</td>

					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">978</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">984</td>
					<td class="done">998</td>

					<td class="done">985</td>
					<td class="done">980</td>
					<td class="done">968</td>
					<td class="done">996</td>
					<td class="done">970</td>
					<td class="done">987</td>

					<td class="done">982</td>
					<td class="done">977</td>
					<td class="done">973</td>
					<td class="done">994</td>
					<td class="done">946</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">989</td>
		</tr>
			<tr class="line">
			<td>12</td>
			<td class="team">ROFLCOPTER!</td>
			<td>

					21694
			</td>
			<td>
					3000
			</td>
			<td>
					30
			</td>
					<td class="done">966</td>
					<td class="empty">X</td>

					<td class="done">981</td>
					<td class="done">1000</td>
					<td class="done">982</td>
					<td class="done">953</td>
					<td class="done">995</td>
					<td class="empty">X</td>

					<td class="done">985</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">978</td>
					<td class="empty">X</td>

					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="done">988</td>

					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="done">996</td>

					<td class="done">994</td>
		</tr>
			<tr class="line">
			<td>13</td>
			<td class="team">Tučňák s tučňákem</td>
			<td>
					21681
			</td>

			<td>
					2000
			</td>
			<td>
					90
			</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">973</td>

					<td class="done">987</td>
					<td class="done">980</td>
					<td class="done">990</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="done">995</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">995</td>
					<td class="done">987</td>
					<td class="done">1000</td>

					<td class="done">993</td>
					<td class="done">988</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>

					<td class="done">977</td>
					<td class="done">997</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">998</td>

		</tr>
			<tr class="line">
			<td>14</td>
			<td class="team">Maséři jako hovado</td>
			<td>
					21637
			</td>
			<td>

					3000
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">996</td>

					<td class="done">961</td>
					<td class="done">992</td>
					<td class="done">984</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="done">993</td>

					<td class="done">996</td>
					<td class="done">988</td>
					<td class="done">999</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">986</td>
					<td class="done">977</td>
					<td class="done">988</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">953</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="done">961</td>

		</tr>
			<tr class="line">
			<td>15</td>
			<td class="team">Megatim</td>
			<td>
					21321
			</td>
			<td>

					2000
			</td>
			<td>
					140
			</td>
					<td class="done">975</td>
					<td class="done">992</td>
					<td class="empty">X</td>

					<td class="done">984</td>
					<td class="done">984</td>
					<td class="done">938</td>
					<td class="done">973</td>
					<td class="done">994</td>
					<td class="done">966</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">944</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="done">966</td>

					<td class="done">964</td>
					<td class="done">968</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">959</td>

					<td class="done">974</td>
					<td class="done">977</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="done">986</td>

		</tr>
			<tr class="line">
			<td>16</td>
			<td class="team">Kokokel</td>
			<td>
					20969
			</td>
			<td>

					2500
			</td>
			<td>
					120
			</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="done">989</td>

					<td class="done">969</td>
					<td class="done">999</td>
					<td class="done">999</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="done">961</td>

					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">946</td>
					<td class="done">988</td>
					<td class="done">986</td>
					<td class="done">999</td>

					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">964</td>

					<td class="done">984</td>
					<td class="done">970</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">978</td>

		</tr>
			<tr class="line">
			<td>17</td>
			<td class="team">Hoď si kostkou</td>
			<td>
					20549
			</td>
			<td>

					2000
			</td>
			<td>
					60
			</td>
					<td class="done">981</td>
					<td class="done">988</td>
					<td class="done">983</td>

					<td class="done">972</td>
					<td class="done">962</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>

					<td class="done">993</td>
					<td class="done">989</td>
					<td class="done">974</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="done">997</td>

					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">988</td>
					<td class="done">990</td>
					<td class="done">958</td>

					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>18</td>
			<td class="team">Borci v uvozovkách</td>
			<td>
					20547
			</td>
			<td>

					3000
			</td>
			<td>
					90
			</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="done">982</td>

					<td class="done">975</td>
					<td class="done">994</td>
					<td class="done">950</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">997</td>

					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">998</td>

					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">962</td>

					<td class="empty">X</td>
					<td class="done">954</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="done">995</td>

		</tr>
			<tr class="line">
			<td>19</td>
			<td class="team">Tweety neni kura</td>
			<td>
					20523
			</td>
			<td>

					2000
			</td>
			<td>
					120
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">974</td>

					<td class="done">971</td>
					<td class="done">963</td>
					<td class="done">952</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">981</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="done">983</td>
					<td class="done">984</td>
					<td class="empty">X</td>

					<td class="done">989</td>
					<td class="done">978</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">975</td>

					<td class="done">988</td>
					<td class="done">985</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="done">987</td>

		</tr>
			<tr class="line">
			<td>20</td>
			<td class="team">Sloniky v hmle</td>
			<td>
					20190
			</td>
			<td>

					2500
			</td>
			<td>
					80
			</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">995</td>

					<td class="done">981</td>
					<td class="done">983</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">991</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">999</td>
					<td class="done">996</td>
					<td class="empty">X</td>

					<td class="done">988</td>
					<td class="done">972</td>
					<td class="done">983</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">998</td>

					<td class="done">994</td>
					<td class="done">991</td>
					<td class="done">938</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>

					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>

					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>

					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>

					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>

					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>21</td>
			<td class="team">Dokonalost netřeba</td>

			<td>
					19499
			</td>
			<td>
					2000
			</td>
			<td>
					80
			</td>
					<td class="done">973</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">949</td>
					<td class="done">996</td>
					<td class="done">993</td>
					<td class="done">977</td>

					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">986</td>
					<td class="done">973</td>

					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="done">970</td>
					<td class="done">975</td>
					<td class="done">968</td>
					<td class="empty">X</td>

					<td class="done">998</td>
					<td class="done">976</td>
					<td class="done">991</td>
					<td class="done">966</td>
					<td class="done">977</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">963</td>
		</tr>
			<tr class="line">
			<td>22</td>
			<td class="team">Červený trpaslík</td>
			<td>

					19098
			</td>
			<td>
					1500
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">1000</td>
					<td class="done">957</td>
					<td class="done">988</td>
					<td class="done">997</td>
					<td class="done">986</td>
					<td class="empty">X</td>

					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">989</td>
					<td class="done">993</td>

					<td class="done">990</td>
					<td class="done">966</td>
					<td class="done">962</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">982</td>
					<td class="done">993</td>
					<td class="done">974</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">974</td>
		</tr>
			<tr class="line">
			<td>23</td>
			<td class="team">Diamhra</td>
			<td>
					19021
			</td>

			<td>
					2500
			</td>
			<td>
					30
			</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="done">947</td>
					<td class="empty">X</td>
					<td class="done">974</td>

					<td class="done">974</td>
					<td class="done">965</td>
					<td class="done">985</td>
					<td class="done">991</td>
					<td class="done">993</td>
					<td class="done">991</td>

					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="done">963</td>
					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="done">962</td>

		</tr>
			<tr class="line">
			<td>24</td>
			<td class="team">Selátka</td>
			<td>
					18642
			</td>
			<td>

					2000
			</td>
			<td>
					40
			</td>
					<td class="done">974</td>
					<td class="done">987</td>
					<td class="empty">X</td>

					<td class="done">991</td>
					<td class="done">1000</td>
					<td class="done">998</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">976</td>

					<td class="empty">X</td>
					<td class="done">1000</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">949</td>

					<td class="done">975</td>
					<td class="done">969</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">984</td>

		</tr>
			<tr class="line">
			<td>25</td>
			<td class="team">Trosecnici</td>
			<td>
					18534
			</td>
			<td>

					2000
			</td>
			<td>
					30
			</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">998</td>

					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="done">957</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="done">996</td>
					<td class="done">990</td>
					<td class="done">962</td>

					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">971</td>

					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="done">966</td>

		</tr>
			<tr class="line">
			<td>26</td>
			<td class="team">Ghent tweewieler</td>
			<td>
					17651
			</td>
			<td>

					1000
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="empty">X</td>

					<td class="done">967</td>
					<td class="done">979</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">1000</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="done">987</td>

					<td class="done">981</td>
					<td class="done">985</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">992</td>
					<td class="done">975</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="done">972</td>

		</tr>
			<tr class="line">
			<td>27</td>
			<td class="team">Cinquecento</td>
			<td>
					16502
			</td>
			<td>

					2000
			</td>
			<td>
					110
			</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="done">990</td>

					<td class="done">953</td>
					<td class="done">990</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">956</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="done">945</td>
					<td class="done">989</td>
					<td class="empty">X</td>

					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">982</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">940</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>

		</tr>
			<tr class="line">
			<td>28</td>
			<td class="team">Minimálne rýchlejšie</td>
			<td>
					16022
			</td>
			<td>

					1500
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">978</td>

					<td class="done">965</td>
					<td class="done">969</td>
					<td class="done">946</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="done">964</td>

					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">967</td>

					<td class="done">990</td>
					<td class="done">993</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="done">981</td>

		</tr>
			<tr class="line">
			<td>29</td>
			<td class="team">|_3&quot;|&quot;|\||´ |\/|32|)|</td>
			<td>
					16021
			</td>

			<td>
					1500
			</td>
			<td>
					80
			</td>
					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">950</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="done">964</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">981</td>

					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>

					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">973</td>

		</tr>
			<tr class="line">
			<td>30</td>
			<td class="team">GastrO&lt;enter&gt;O(log)</td>
			<td>
					15699
			</td>

			<td>
					1000
			</td>
			<td>
					20
			</td>
					<td class="done">999</td>
					<td class="done">997</td>
					<td class="done">987</td>

					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="done">935</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>

					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="done">946</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="done">974</td>

					<td class="done">985</td>
					<td class="done">992</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>

					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>

					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>

					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>

					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>

					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>31</td>
			<td class="team">Jak se nám líbí!</td>

			<td>
					15621
			</td>
			<td>
					2000
			</td>
			<td>
					60
			</td>
					<td class="done">994</td>

					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="done">975</td>

					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="done">967</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">995</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">948</td>
					<td class="empty">X</td>

					<td class="done">992</td>
					<td class="done">971</td>
		</tr>
			<tr class="line">
			<td>32</td>
			<td class="team">Žufouni</td>
			<td>

					15121
			</td>
			<td>
					1500
			</td>
			<td>
					70
			</td>
					<td class="done">989</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">991</td>
					<td class="done">977</td>
					<td class="empty">X</td>

					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="done">973</td>
					<td class="done">986</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">982</td>
					<td class="done">951</td>
					<td class="empty">X</td>
					<td class="done">968</td>

					<td class="done">992</td>
		</tr>
			<tr class="line">
			<td>33</td>
			<td class="team">Carpe Diem</td>
			<td>
					14606
			</td>

			<td>
					1000
			</td>
			<td>
					80
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="done">978</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="done">992</td>
					<td class="done">981</td>
					<td class="empty">X</td>

					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">957</td>

					<td class="done">978</td>
					<td class="done">986</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>34</td>
			<td class="team">Bedrunky</td>
			<td>
					14447
			</td>
			<td>

					1000
			</td>
			<td>
					150
			</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">999</td>
					<td class="done">970</td>
					<td class="done">949</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="done">968</td>

					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">951</td>
					<td class="empty">X</td>
					<td class="done">984</td>
					<td class="done">954</td>

					<td class="done">1000</td>
					<td class="done">983</td>
					<td class="done">950</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>35</td>
			<td class="team">Sráči</td>
			<td>
					14162
			</td>
			<td>

					1500
			</td>
			<td>
					30
			</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="done">971</td>

					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">992</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>

					<td class="done">999</td>
					<td class="done">960</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>36</td>
			<td class="team">Heuréka</td>
			<td>
					14102
			</td>
			<td>

					1500
			</td>
			<td>
					20
			</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">937</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">958</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="done">951</td>
					<td class="empty">X</td>
					<td class="done">995</td>

					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">967</td>

		</tr>
			<tr class="line">
			<td>37</td>
			<td class="team">dušou blondínky</td>
			<td>
					14076
			</td>
			<td>

					1500
			</td>
			<td>
					70
			</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">936</td>
					<td class="done">988</td>
					<td class="done">995</td>
					<td class="done">979</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">945</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="done">953</td>

					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>

					<td class="empty">X</td>
					<td class="done">999</td>
					<td class="done">939</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">983</td>

		</tr>
			<tr class="line">
			<td>38</td>
			<td class="team">Faltus Team</td>
			<td>
					14074
			</td>
			<td>

					1500
			</td>
			<td>
					30
			</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="done">963</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="done">963</td>

					<td class="done">972</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">946</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">968</td>

		</tr>
			<tr class="line">
			<td>39</td>
			<td class="team">Ve jménu Hříbečka</td>
			<td>
					13952
			</td>
			<td>

					1500
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>

					<td class="done">956</td>
					<td class="done">965</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">941</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="done">967</td>

					<td class="empty">X</td>
					<td class="done">964</td>
					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>

					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="done">941</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>40</td>
			<td class="team">Stěrači</td>
			<td>
					13330
			</td>
			<td>

					1000
			</td>
			<td>
					240
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>

					<td class="done">943</td>
					<td class="done">964</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">967</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">956</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="done">993</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">953</td>

					<td class="done">986</td>
					<td class="done">956</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>

					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>

					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>

					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>

					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>

					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>41</td>
			<td class="team">Hrst ve světě</td>

			<td>
					13188
			</td>
			<td>
					1500
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="done">995</td>
					<td class="done">986</td>
					<td class="done">958</td>
					<td class="done">974</td>

					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">991</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>42</td>
			<td class="team">Vepřová kachna</td>
			<td>

					13176
			</td>
			<td>
					1500
			</td>
			<td>
					110
			</td>
					<td class="done">963</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="done">948</td>
					<td class="done">1000</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">1000</td>
					<td class="done">982</td>
					<td class="done">989</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="done">984</td>

					<td class="done">997</td>
		</tr>
			<tr class="line">
			<td>43</td>
			<td class="team">KVÍK!</td>
			<td>
					12923
			</td>

			<td>
					1500
			</td>
			<td>
					160
			</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="done">994</td>

					<td class="done">942</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">937</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="done">972</td>

					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">943</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="done">988</td>

		</tr>
			<tr class="line">
			<td>44</td>
			<td class="team">Zrychlený TEP</td>
			<td>
					12726
			</td>
			<td>

					1000
			</td>
			<td>
					70
			</td>
					<td class="done">977</td>
					<td class="done">983</td>
					<td class="empty">X</td>

					<td class="done">978</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">968</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="done">970</td>
					<td class="done">997</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>

					<td class="done">979</td>
					<td class="done">996</td>
					<td class="done">991</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">991</td>

		</tr>
			<tr class="line">
			<td>45</td>
			<td class="team">Guinea Pigs</td>
			<td>
					12712
			</td>
			<td>

					1000
			</td>
			<td>
					0
			</td>
					<td class="done">968</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">999</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="done">955</td>

					<td class="done">975</td>
					<td class="done">966</td>
					<td class="done">965</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">975</td>

		</tr>
			<tr class="line">
			<td>46</td>
			<td class="team">Ztráty a Nálezy</td>
			<td>
					12607
			</td>
			<td>

					1000
			</td>
			<td>
					110
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="done">949</td>
					<td class="empty">X</td>
					<td class="done">957</td>

					<td class="done">985</td>
					<td class="done">993</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>47</td>
			<td class="team">interwin</td>
			<td>
					12441
			</td>
			<td>

					1000
			</td>
			<td>
					220
			</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">955</td>
					<td class="done">998</td>
					<td class="done">1000</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">947</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="done">959</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>

					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>48</td>
			<td class="team">WeSwearSheWas18</td>
			<td>
					12380
			</td>
			<td>

					1000
			</td>
			<td>
					180
			</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">947</td>
					<td class="done">978</td>
					<td class="done">942</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">949</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="done">959</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">963</td>

					<td class="empty">X</td>
					<td class="done">988</td>
					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>49</td>
			<td class="team">Soldiers of Congruence</td>
			<td>
					12023
			</td>
			<td>

					500
			</td>
			<td>
					40
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">973</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">939</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="done">989</td>

					<td class="done">990</td>
					<td class="done">982</td>
					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">949</td>
					<td class="done">942</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>

		</tr>
			<tr class="line">
			<td>50</td>
			<td class="team">Tykve</td>
			<td>
					11607
			</td>
			<td>

					1000
			</td>
			<td>
					50
			</td>
					<td class="done">971</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">983</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">943</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">977</td>
					<td class="done">983</td>
					<td class="done">948</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="done">972</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">945</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>

		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>

					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>

					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>

					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>

					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>

					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>51</td>
			<td class="team">interlososi</td>

			<td>
					11595
			</td>
			<td>
					1000
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="done">997</td>
					<td class="done">957</td>
					<td class="done">976</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">957</td>
					<td class="done">975</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">949</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">962</td>
					<td class="done">999</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">964</td>
		</tr>
			<tr class="line">
			<td>52</td>
			<td class="team">GBN</td>
			<td>

					11592
			</td>
			<td>
					1000
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="done">961</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">953</td>
					<td class="done">943</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="done">969</td>

					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>53</td>
			<td class="team">para-N-methylaminoazobenzen</td>
			<td>
					11116
			</td>

			<td>
					500
			</td>
			<td>
					90
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">994</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">935</td>
					<td class="done">984</td>
					<td class="empty">X</td>
					<td class="done">983</td>

					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="done">990</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>54</td>
			<td class="team">Dopplerův jev</td>
			<td>
					9671
			</td>
			<td>

					1000
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">940</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">951</td>

					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">956</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="done">996</td>

		</tr>
			<tr class="line">
			<td>55</td>
			<td class="team">Pirate Shrimp</td>
			<td>
					9549
			</td>
			<td>

					1000
			</td>
			<td>
					80
			</td>
					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="done">979</td>

					<td class="done">940</td>
					<td class="empty">X</td>
					<td class="done">939</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">962</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">956</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">944</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>56</td>
			<td class="team">LuMPi</td>
			<td>
					9123
			</td>
			<td>

					500
			</td>
			<td>
					150
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">964</td>
					<td class="empty">X</td>
					<td class="done">945</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">968</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="done">973</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">997</td>

					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>

		</tr>
			<tr class="line">
			<td>57</td>
			<td class="team">Bazinga</td>
			<td>
					8803
			</td>
			<td>

					1000
			</td>
			<td>
					50
			</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">962</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">982</td>
					<td class="empty">X</td>
					<td class="done">987</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">994</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="done">986</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">987</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>58</td>
			<td class="team">Virus a Magor</td>
			<td>
					8718
			</td>
			<td>

					1000
			</td>
			<td>
					0
			</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">977</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">936</td>
					<td class="done">990</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">947</td>

					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>59</td>
			<td class="team">Počtáři</td>
			<td>
					8674
			</td>
			<td>

					1000
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">952</td>
					<td class="empty">X</td>
					<td class="done">940</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">973</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">979</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">968</td>

					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>60</td>
			<td class="team">Nevim dál</td>
			<td>
					7709
			</td>
			<td>

					0
			</td>
			<td>
					60
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">987</td>
					<td class="done">950</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>

					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>

					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>

					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>

					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>

					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>61</td>
			<td class="team">Big Brothers</td>

			<td>
					7673
			</td>
			<td>
					0
			</td>
			<td>
					100
			</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="done">947</td>
					<td class="done">997</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">974</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">961</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">965</td>
		</tr>
			<tr class="line">
			<td>62</td>
			<td class="team">IT Arsenal</td>
			<td>

					7615
			</td>
			<td>
					0
			</td>
			<td>
					130
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">966</td>
					<td class="empty">X</td>
					<td class="done">974</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">989</td>
					<td class="done">950</td>
					<td class="done">998</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="done">965</td>
					<td class="done">955</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>63</td>
			<td class="team">Acervus aren</td>
			<td>
					7571
			</td>

			<td>
					1000
			</td>
			<td>
					170
			</td>
					<td class="done">961</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">954</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">955</td>
					<td class="done">953</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">963</td>
					<td class="done">979</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>64</td>
			<td class="team">Svět v hrsti</td>
			<td>
					6667
			</td>
			<td>

					0
			</td>
			<td>
					120
			</td>
					<td class="done">959</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">985</td>
					<td class="empty">X</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">942</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">945</td>

					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="done">993</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>65</td>
			<td class="team">GKJ_Elite_Team</td>
			<td>
					6517
			</td>
			<td>

					0
			</td>
			<td>
					160
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">944</td>
					<td class="done">967</td>
					<td class="done">941</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">948</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">954</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">965</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>66</td>
			<td class="team">pivári</td>
			<td>
					6304
			</td>
			<td>

					500
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">945</td>
					<td class="empty">X</td>
					<td class="done">981</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">984</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">976</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">950</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>67</td>
			<td class="team">proGenius Team !</td>
			<td>
					6189
			</td>
			<td>

					500
			</td>
			<td>
					120
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">993</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">983</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">938</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">975</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>68</td>
			<td class="team">OneManTeam</td>
			<td>
					4855
			</td>
			<td>

					0
			</td>
			<td>
					50
			</td>
					<td class="empty">X</td>
					<td class="done">995</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">998</td>
					<td class="done">970</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">985</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">957</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>69</td>
			<td class="team">Proč ne 32</td>
			<td>
					4799
			</td>
			<td>

					0
			</td>
			<td>
					80
			</td>
					<td class="done">958</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">974</td>
					<td class="done">974</td>
					<td class="done">994</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>70</td>
			<td class="team">Pan Tofle</td>
			<td>
					4753
			</td>
			<td>

					0
			</td>
			<td>
					80
			</td>
					<td class="done">967</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="done">975</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">972</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">970</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">949</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>

					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>

					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>

					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>

					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>

					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>71</td>
			<td class="team">Severus</td>

			<td>
					3835
			</td>
			<td>
					0
			</td>
			<td>
					10
			</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">946</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">979</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">942</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">978</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>72</td>
			<td class="team">voy-c-ger</td>
			<td>

					3721
			</td>
			<td>
					0
			</td>
			<td>
					140
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">969</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">952</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">989</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>73</td>
			<td class="team">My nic – to samo</td>
			<td>
					1966
			</td>

			<td>
					0
			</td>
			<td>
					10
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="done">980</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">996</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>74</td>
			<td class="team">KAPAcity</td>
			<td>
					1828
			</td>
			<td>

					0
			</td>
			<td>
					120
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">951</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">997</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>75</td>
			<td class="team">Lentilci</td>
			<td>
					976
			</td>
			<td>

					0
			</td>
			<td>
					10
			</td>
					<td class="done">986</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>76</td>
			<td class="team">Šneci</td>
			<td>
					960
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="done">960</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>77</td>
			<td class="team">Bubliny</td>
			<td>
					0
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>78</td>
			<td class="team">GraMLy</td>
			<td>
					0
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>79</td>
			<td class="team">hmyzáci</td>
			<td>
					0
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>80</td>
			<td class="team">Švejďáci</td>
			<td>
					0
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>

					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>

					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>

					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>

					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>

					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>81</td>
			<td class="team">Zatím Nevím</td>

			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>82</td>
			<td class="team">zero_power_zero</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>83</td>
			<td class="team">Lasice</td>
			<td>
					0
			</td>

			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>84</td>
			<td class="team">mechanický pomeranč</td>
			<td>
					0
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>85</td>
			<td class="team">Partyzán</td>
			<td>
					0
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>86</td>
			<td class="team">DesertTeam</td>
			<td>
					0
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>87</td>
			<td class="team">Krucipísek</td>
			<td>
					0
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>88</td>
			<td class="team">Lehká demence</td>
			<td>
					0
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>89</td>
			<td class="team">Matesovic</td>
			<td>
					0
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr class="line">
			<td>90</td>
			<td class="team">Specialita šéfkuchaře</td>
			<td>
					0
			</td>
			<td>

					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

		</tr>
			<tr>
				<th>#</th>
				<th>Tým</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>

					<th>P1</th>
					<th>P2</th>
					<th>P3</th>
					<th>L1</th>
					<th>L2</th>
					<th>L3</th>

					<th>S1</th>
					<th>S2</th>
					<th>S3</th>
					<th>P4</th>
					<th>P5</th>
					<th>P6</th>

					<th>L4</th>
					<th>L5</th>
					<th>L6</th>
					<th>S4</th>
					<th>S5</th>
					<th>S6</th>

					<th>P7</th>
					<th>P8</th>
					<th>P9</th>
					<th>L7</th>
					<th>L8</th>
					<th>L9</th>

					<th>S7</th>
					<th>S8</th>
					<th>S9</th>
			</tr>
			<tr>
			<td>91</td>
			<td class="team">Svědkové Baronovi</td>

			<td>
					0
			</td>
			<td>
					0
			</td>
			<td>
					0
			</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
		</tr>
			<tr class="line">
			<td>92</td>
			<td class="team">Organizátoři</td>
			<td>

					-30
			</td>
			<td>
					0
			</td>
			<td>
					30
			</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>
					<td class="empty">X</td>

					<td class="empty">X</td>
		</tr>
	</table>
{/block}
