{extends ../layout.phtml}

{block #content}
    <div id="submenu">
	<ul>
		<li>
			<a href="{plink Stats:default}" title="Výsledky">Výsledky</a>
			<ul>
				<li><a href="{plink Stats:default}#{=TeamsModel::HIGH_SCHOOL}" title="Výsledky - středoškoláci">středoškoláci</a></li>
				<li><a href="{plink Stats:default}#{=TeamsModel::COLLEGE}" title="Výsledky - vysokoškoláci">vysokoškoláci</a></li>
				<li><a href="{plink Stats:default}#{=TeamsModel::OTHER}" title="Výsledky - ostatní">ostatní</a></li>
			</ul>
		</li>
		<li><a href="{plink Stats:detail}" title="Podrobné výsledky">Podrobné výsledky</a></li>
		<li><a href="{plink Stats:tasks}" title="Statistiky úkolů">Statistiky úkolů</a></li>
	</ul>
    </div>
    <div id="subcontent">
	{block #subcontent}
	{/block}
    </div>
{/block}